//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 The Ingate Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AllowedRoutesSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.AllowedRoutesSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Backend) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.Backend"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BackendEndpoint) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.BackendEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BackendList) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.BackendList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BackendRef) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.BackendRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BackendSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.BackendSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in BackendStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.BackendStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Certificate) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.Certificate"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CertificateList) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.CertificateList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CertificateSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.CertificateSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CertificateStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.CertificateStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DNSBackendSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.DNSBackendSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Gateway) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.Gateway"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewayList) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewayList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewayListener) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewayListener"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewayListenerStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewayListenerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewaySpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewaySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewayStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewayStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GatewayTLSConfig) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.GatewayTLSConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeader) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPHeader"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeaderFilter) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPHeaderFilter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPHeaderMatch) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPHeaderMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPPathMatch) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPPathMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPPathModifier) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPPathModifier"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPRouteFilter) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPRouteFilter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPRouteMatch) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPRouteMatch"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HTTPURLRewriteFilter) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.HTTPURLRewriteFilter"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LoadBalanceSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.LoadBalanceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalObjectReference) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.LocalObjectReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ParentReference) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.ParentReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Route) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.Route"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteList) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.RouteList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteParentStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.RouteParentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteRule) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.RouteRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.RouteSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in RouteStatus) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.RouteStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Secret) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.Secret"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecretList) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.SecretList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SecretSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.SecretSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in StaticBackendSpec) OpenAPIModelName() string {
	return "com.github.lgc202.ingate.pkg.apis.gateway.v1alpha1.StaticBackendSpec"
}
