//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Copyright 2026 The Ingate Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&Backend{}, func(obj interface{}) { SetObjectDefaults_Backend(obj.(*Backend)) })
	scheme.AddTypeDefaultingFunc(&BackendList{}, func(obj interface{}) { SetObjectDefaults_BackendList(obj.(*BackendList)) })
	scheme.AddTypeDefaultingFunc(&Gateway{}, func(obj interface{}) { SetObjectDefaults_Gateway(obj.(*Gateway)) })
	scheme.AddTypeDefaultingFunc(&GatewayList{}, func(obj interface{}) { SetObjectDefaults_GatewayList(obj.(*GatewayList)) })
	scheme.AddTypeDefaultingFunc(&ResolvedGateway{}, func(obj interface{}) { SetObjectDefaults_ResolvedGateway(obj.(*ResolvedGateway)) })
	scheme.AddTypeDefaultingFunc(&ResolvedGatewayList{}, func(obj interface{}) { SetObjectDefaults_ResolvedGatewayList(obj.(*ResolvedGatewayList)) })
	scheme.AddTypeDefaultingFunc(&Route{}, func(obj interface{}) { SetObjectDefaults_Route(obj.(*Route)) })
	scheme.AddTypeDefaultingFunc(&RouteList{}, func(obj interface{}) { SetObjectDefaults_RouteList(obj.(*RouteList)) })
	return nil
}

func SetObjectDefaults_Backend(in *Backend) {
	SetDefaults_Backend(in)
}

func SetObjectDefaults_BackendList(in *BackendList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Backend(a)
	}
}

func SetObjectDefaults_Gateway(in *Gateway) {
	SetDefaults_Gateway(in)
}

func SetObjectDefaults_GatewayList(in *GatewayList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Gateway(a)
	}
}

func SetObjectDefaults_ResolvedGateway(in *ResolvedGateway) {
	SetDefaults_ResolvedGateway(in)
}

func SetObjectDefaults_ResolvedGatewayList(in *ResolvedGatewayList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_ResolvedGateway(a)
	}
}

func SetObjectDefaults_Route(in *Route) {
	SetDefaults_Route(in)
}

func SetObjectDefaults_RouteList(in *RouteList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_Route(a)
	}
}
