// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package adminapi

import (
	"context"
	"github.com/go-kratos/kratos/v3"
	"github.com/google/wire"
	"github.com/lgc202/ingate/internal/adminapi/biz"
	"github.com/lgc202/ingate/internal/adminapi/biz/aiusage"
	"github.com/lgc202/ingate/internal/adminapi/biz/caller"
	"github.com/lgc202/ingate/internal/adminapi/biz/certificate"
	"github.com/lgc202/ingate/internal/adminapi/biz/gateway"
	"github.com/lgc202/ingate/internal/adminapi/biz/headertransformation"
	"github.com/lgc202/ingate/internal/adminapi/biz/iprestriction"
	"github.com/lgc202/ingate/internal/adminapi/biz/mockresponse"
	"github.com/lgc202/ingate/internal/adminapi/biz/pluginsource"
	"github.com/lgc202/ingate/internal/adminapi/biz/ratelimit"
	"github.com/lgc202/ingate/internal/adminapi/biz/request"
	"github.com/lgc202/ingate/internal/adminapi/biz/route"
	"github.com/lgc202/ingate/internal/adminapi/biz/tokenquota"
	"github.com/lgc202/ingate/internal/adminapi/biz/traffic"
	"github.com/lgc202/ingate/internal/adminapi/biz/upstream"
	"github.com/lgc202/ingate/internal/adminapi/biz/wasmplugin"
	"github.com/lgc202/ingate/internal/adminapi/conf"
	"github.com/lgc202/ingate/internal/adminapi/data/aiextproc"
	"github.com/lgc202/ingate/internal/adminapi/data/analytics"
	"github.com/lgc202/ingate/internal/adminapi/data/apiserver"
	"github.com/lgc202/ingate/internal/adminapi/data/plugincatalog"
	"github.com/lgc202/ingate/internal/adminapi/server"
	aiusage2 "github.com/lgc202/ingate/internal/adminapi/service/aiusage"
	caller2 "github.com/lgc202/ingate/internal/adminapi/service/caller"
	certificate2 "github.com/lgc202/ingate/internal/adminapi/service/certificate"
	gateway2 "github.com/lgc202/ingate/internal/adminapi/service/gateway"
	headertransformation2 "github.com/lgc202/ingate/internal/adminapi/service/headertransformation"
	"github.com/lgc202/ingate/internal/adminapi/service/health"
	iprestriction2 "github.com/lgc202/ingate/internal/adminapi/service/iprestriction"
	mockresponse2 "github.com/lgc202/ingate/internal/adminapi/service/mockresponse"
	pluginsource2 "github.com/lgc202/ingate/internal/adminapi/service/pluginsource"
	ratelimit2 "github.com/lgc202/ingate/internal/adminapi/service/ratelimit"
	request2 "github.com/lgc202/ingate/internal/adminapi/service/request"
	route2 "github.com/lgc202/ingate/internal/adminapi/service/route"
	tokenquota2 "github.com/lgc202/ingate/internal/adminapi/service/tokenquota"
	traffic2 "github.com/lgc202/ingate/internal/adminapi/service/traffic"
	upstream2 "github.com/lgc202/ingate/internal/adminapi/service/upstream"
	wasmplugin2 "github.com/lgc202/ingate/internal/adminapi/service/wasmplugin"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(contextContext context.Context, confServer *conf.Server, data *conf.Data, logger *slog.Logger, adminapiServiceInstanceID serviceInstanceID) (*kratos.App, func(), error) {
	clientConn, cleanup, err := analytics.NewClient(contextContext, data, logger)
	if err != nil {
		return nil, nil, err
	}
	aiUsageRepository := analytics.NewAIUsageRepository(clientConn)
	usecase := aiusage.NewUsecase(aiUsageRepository)
	service := aiusage2.NewService(usecase)
	versionedInterface, err := apiserver.NewClient(data)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	callerStore := apiserver.NewCallerStore(versionedInterface)
	routeStore := apiserver.NewRouteStore(versionedInterface)
	tokenQuotaPolicyStore := apiserver.NewTokenQuotaPolicyStore(versionedInterface)
	callerUsecase := caller.NewUsecase(callerStore, routeStore, tokenQuotaPolicyStore)
	callerService := caller2.NewService(callerUsecase)
	gatewayStore := apiserver.NewGatewayStore(versionedInterface)
	certificateStore := apiserver.NewCertificateStore(versionedInterface)
	rateLimitPolicyStore := apiserver.NewRateLimitPolicyStore(versionedInterface)
	ipRestrictionPolicyStore := apiserver.NewIPRestrictionPolicyStore(versionedInterface)
	headerTransformationPolicyStore := apiserver.NewHeaderTransformationPolicyStore(versionedInterface)
	mockResponsePolicyStore := apiserver.NewMockResponsePolicyStore(versionedInterface)
	policyUsageFinder := biz.NewPolicyUsageFinder(rateLimitPolicyStore, ipRestrictionPolicyStore, headerTransformationPolicyStore, mockResponsePolicyStore)
	gatewayUsecase := gateway.NewUsecase(gatewayStore, routeStore, certificateStore, policyUsageFinder)
	gatewayService := gateway2.NewService(gatewayUsecase)
	upstreamStore := apiserver.NewUpstreamStore(versionedInterface)
	routeUsecase := route.NewUsecase(routeStore, gatewayStore, upstreamStore, callerStore, policyUsageFinder)
	routeService := route2.NewService(routeUsecase)
	upstreamUsecase := upstream.NewUsecase(upstreamStore, routeStore)
	upstreamService := upstream2.NewService(upstreamUsecase)
	certificateUsecase := certificate.NewUsecase(certificateStore, gatewayStore)
	certificateService := certificate2.NewService(certificateUsecase)
	ratelimitUsecase := ratelimit.NewUsecase(rateLimitPolicyStore, gatewayStore, routeStore)
	ratelimitService := ratelimit2.NewService(ratelimitUsecase)
	iprestrictionUsecase := iprestriction.NewUsecase(ipRestrictionPolicyStore, gatewayStore, routeStore)
	iprestrictionService := iprestriction2.NewService(iprestrictionUsecase)
	requestRepository := analytics.NewRequestRepository(clientConn)
	requestUsecase := request.NewUsecase(requestRepository)
	requestService := request2.NewService(requestUsecase)
	trafficRepository := analytics.NewTrafficRepository(clientConn)
	trafficUsecase := traffic.NewUsecase(trafficRepository)
	trafficService := traffic2.NewService(trafficUsecase)
	tokenQuotaUsageServiceClient, cleanup2, err := aiextproc.NewClient(contextContext, data, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tokenQuotaUsageReader := aiextproc.NewTokenQuotaUsageReader(tokenQuotaUsageServiceClient)
	tokenquotaUsecase := tokenquota.NewUsecase(tokenQuotaPolicyStore, callerStore, tokenQuotaUsageReader)
	tokenquotaService := tokenquota2.NewService(tokenquotaUsecase)
	healthService := health.NewService()
	wasmPluginStore := apiserver.NewWasmPluginStore(versionedInterface)
	pluginInstallationChecker := biz.NewPluginInstallationChecker(wasmPluginStore)
	headertransformationUsecase := headertransformation.NewUsecase(headerTransformationPolicyStore, routeStore, pluginInstallationChecker)
	headertransformationService := headertransformation2.NewService(headertransformationUsecase)
	mockresponseUsecase := mockresponse.NewUsecase(mockResponsePolicyStore, routeStore, pluginInstallationChecker)
	mockresponseService := mockresponse2.NewService(mockresponseUsecase)
	pluginUsageFinder := biz.NewPluginUsageFinder(headerTransformationPolicyStore, mockResponsePolicyStore)
	pluginSourceStore := apiserver.NewPluginSourceStore(versionedInterface)
	catalog := plugincatalog.NewCatalog(data, pluginSourceStore, logger)
	wasmpluginUsecase := wasmplugin.NewUsecase(wasmPluginStore, pluginUsageFinder, catalog)
	wasmpluginService := wasmplugin2.NewService(wasmpluginUsecase)
	pluginsourceUsecase := pluginsource.NewUsecase(pluginSourceStore, catalog)
	pluginsourceService := pluginsource2.NewService(pluginsourceUsecase)
	services := server.NewServices(service, callerService, gatewayService, routeService, upstreamService, certificateService, ratelimitService, iprestrictionService, requestService, trafficService, tokenquotaService, healthService, headertransformationService, mockresponseService, wasmpluginService, pluginsourceService)
	httpServer := server.NewHTTPServer(confServer, logger, services)
	grpcServer := server.NewGRPCServer(confServer, logger, services)
	app := newKratosApp(logger, confServer, httpServer, grpcServer, catalog, adminapiServiceInstanceID)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// Admin API 按资源拆成 biz 子包，而子包依赖根 biz 的共享边界；
// 根包不能反向导入子包，因此由应用装配文件汇总各资源用例。
var bizProviderSet = wire.NewSet(biz.NewPolicyUsageFinder, biz.NewPluginUsageFinder, biz.NewPluginInstallationChecker, wire.Bind(new(wasmplugin.PolicyUsageLister), new(*biz.PluginUsageFinder)), aiusage.NewUsecase, caller.NewUsecase, gateway.NewUsecase, headertransformation.NewUsecase, mockresponse.NewUsecase, route.NewUsecase, upstream.NewUsecase, certificate.NewUsecase, ratelimit.NewUsecase, iprestriction.NewUsecase, pluginsource.NewUsecase, request.NewUsecase, traffic.NewUsecase, tokenquota.NewUsecase, wasmplugin.NewUsecase)

// service 子包同样依赖根 service 的协议转换能力，由应用装配文件统一汇总。
var serviceProviderSet = wire.NewSet(aiusage2.NewService, caller2.NewService, gateway2.NewService, headertransformation2.NewService, mockresponse2.NewService, route2.NewService, upstream2.NewService, certificate2.NewService, ratelimit2.NewService, iprestriction2.NewService, pluginsource2.NewService, request2.NewService, traffic2.NewService, tokenquota2.NewService, health.NewService, wasmplugin2.NewService)
