// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: assistant.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 定义 ingate-assistant 的完整进程配置
type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Model         *Model                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Stream        *Stream                `protobuf:"bytes,4,opt,name=stream,proto3" json:"stream,omitempty"`
	Logging       *Logging               `protobuf:"bytes,5,opt,name=logging,proto3" json:"logging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *Bootstrap) GetStream() *Stream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *Bootstrap) GetLogging() *Logging {
	if x != nil {
		return x.Logging
	}
	return nil
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Http            *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	ShutdownTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mysql         *Data_MySQL            `protobuf:"bytes,1,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetMysql() *Data_MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Model struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl         string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ApiKey          string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timeout         *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxOutputTokens uint32                 `protobuf:"varint,5,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	MaxIterations   uint32                 `protobuf:"varint,6,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	Instruction     string                 `protobuf:"bytes,7,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *Model) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Model) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Model) GetMaxOutputTokens() uint32 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *Model) GetMaxIterations() uint32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *Model) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retention     *durationpb.Duration   `protobuf:"bytes,1,opt,name=retention,proto3" json:"retention,omitempty"`
	MaxEvents     uint32                 `protobuf:"varint,2,opt,name=max_events,json=maxEvents,proto3" json:"max_events,omitempty"`
	ReadBlock     *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_block,json=readBlock,proto3" json:"read_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{4}
}

func (x *Stream) GetRetention() *durationpb.Duration {
	if x != nil {
		return x.Retention
	}
	return nil
}

func (x *Stream) GetMaxEvents() uint32 {
	if x != nil {
		return x.MaxEvents
	}
	return 0
}

func (x *Stream) GetReadBlock() *durationpb.Duration {
	if x != nil {
		return x.ReadBlock
	}
	return nil
}

type Logging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	AddSource     bool                   `protobuf:"varint,3,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logging) Reset() {
	*x = Logging{}
	mi := &file_assistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logging) ProtoMessage() {}

func (x *Logging) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logging.ProtoReflect.Descriptor instead.
func (*Logging) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{5}
}

func (x *Logging) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Logging) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logging) GetAddSource() bool {
	if x != nil {
		return x.AddSource
	}
	return false
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_assistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_MySQL struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Database              string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Username              string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password              string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	DialTimeout           *durationpb.Duration   `protobuf:"bytes,5,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	MaxOpenConnections    uint32                 `protobuf:"varint,6,opt,name=max_open_connections,json=maxOpenConnections,proto3" json:"max_open_connections,omitempty"`
	MaxIdleConnections    uint32                 `protobuf:"varint,7,opt,name=max_idle_connections,json=maxIdleConnections,proto3" json:"max_idle_connections,omitempty"`
	ConnectionMaxLifetime *durationpb.Duration   `protobuf:"bytes,8,opt,name=connection_max_lifetime,json=connectionMaxLifetime,proto3" json:"connection_max_lifetime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Data_MySQL) Reset() {
	*x = Data_MySQL{}
	mi := &file_assistant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MySQL) ProtoMessage() {}

func (x *Data_MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MySQL.ProtoReflect.Descriptor instead.
func (*Data_MySQL) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_MySQL) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Data_MySQL) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Data_MySQL) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Data_MySQL) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_MySQL) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_MySQL) GetMaxOpenConnections() uint32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxIdleConnections() uint32 {
	if x != nil {
		return x.MaxIdleConnections
	}
	return 0
}

func (x *Data_MySQL) GetConnectionMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnectionMaxLifetime
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Database      int32                  `protobuf:"varint,3,opt,name=database,proto3" json:"database,omitempty"`
	DialTimeout   *durationpb.Duration   `protobuf:"bytes,4,opt,name=dial_timeout,json=dialTimeout,proto3" json:"dial_timeout,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,5,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,6,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	PoolSize      uint32                 `protobuf:"varint,7,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_assistant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

func (x *Data_Redis) GetDialTimeout() *durationpb.Duration {
	if x != nil {
		return x.DialTimeout
	}
	return nil
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Redis) GetPoolSize() uint32 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

var File_assistant_proto protoreflect.FileDescriptor

const file_assistant_proto_rawDesc = "" +
	"\n" +
	"\x0fassistant.proto\x12\x15ingate.assistant.conf\x1a\x1egoogle/protobuf/duration.proto\"\x98\x02\n" +
	"\tBootstrap\x125\n" +
	"\x06server\x18\x01 \x01(\v2\x1d.ingate.assistant.conf.ServerR\x06server\x12/\n" +
	"\x04data\x18\x02 \x01(\v2\x1b.ingate.assistant.conf.DataR\x04data\x122\n" +
	"\x05model\x18\x03 \x01(\v2\x1c.ingate.assistant.conf.ModelR\x05model\x125\n" +
	"\x06stream\x18\x04 \x01(\v2\x1d.ingate.assistant.conf.StreamR\x06stream\x128\n" +
	"\alogging\x18\x05 \x01(\v2\x1e.ingate.assistant.conf.LoggingR\alogging\"\xd7\x01\n" +
	"\x06Server\x126\n" +
	"\x04http\x18\x01 \x01(\v2\".ingate.assistant.conf.Server.HTTPR\x04http\x12D\n" +
	"\x10shutdown_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1aO\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x9a\x06\n" +
	"\x04Data\x127\n" +
	"\x05mysql\x18\x01 \x01(\v2!.ingate.assistant.conf.Data.MySQLR\x05mysql\x127\n" +
	"\x05redis\x18\x02 \x01(\v2!.ingate.assistant.conf.Data.RedisR\x05redis\x1a\xea\x02\n" +
	"\x05MySQL\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12<\n" +
	"\fdial_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x120\n" +
	"\x14max_open_connections\x18\x06 \x01(\rR\x12maxOpenConnections\x120\n" +
	"\x14max_idle_connections\x18\a \x01(\rR\x12maxIdleConnections\x12Q\n" +
	"\x17connection_max_lifetime\x18\b \x01(\v2\x19.google.protobuf.DurationR\x15connectionMaxLifetime\x1a\xb2\x02\n" +
	"\x05Redis\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\x05R\bdatabase\x12<\n" +
	"\fdial_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vdialTimeout\x12<\n" +
	"\fread_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12\x1b\n" +
	"\tpool_size\x18\a \x01(\rR\bpoolSize\"\xf9\x01\n" +
	"\x05Model\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12*\n" +
	"\x11max_output_tokens\x18\x05 \x01(\rR\x0fmaxOutputTokens\x12%\n" +
	"\x0emax_iterations\x18\x06 \x01(\rR\rmaxIterations\x12 \n" +
	"\vinstruction\x18\a \x01(\tR\vinstruction\"\x9a\x01\n" +
	"\x06Stream\x127\n" +
	"\tretention\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\tretention\x12\x1d\n" +
	"\n" +
	"max_events\x18\x02 \x01(\rR\tmaxEvents\x128\n" +
	"\n" +
	"read_block\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\treadBlock\"V\n" +
	"\aLogging\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"add_source\x18\x03 \x01(\bR\taddSourceB7Z5github.com/lgc202/ingate/internal/assistant/conf;confb\x06proto3"

var (
	file_assistant_proto_rawDescOnce sync.Once
	file_assistant_proto_rawDescData []byte
)

func file_assistant_proto_rawDescGZIP() []byte {
	file_assistant_proto_rawDescOnce.Do(func() {
		file_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)))
	})
	return file_assistant_proto_rawDescData
}

var file_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_assistant_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: ingate.assistant.conf.Bootstrap
	(*Server)(nil),              // 1: ingate.assistant.conf.Server
	(*Data)(nil),                // 2: ingate.assistant.conf.Data
	(*Model)(nil),               // 3: ingate.assistant.conf.Model
	(*Stream)(nil),              // 4: ingate.assistant.conf.Stream
	(*Logging)(nil),             // 5: ingate.assistant.conf.Logging
	(*Server_HTTP)(nil),         // 6: ingate.assistant.conf.Server.HTTP
	(*Data_MySQL)(nil),          // 7: ingate.assistant.conf.Data.MySQL
	(*Data_Redis)(nil),          // 8: ingate.assistant.conf.Data.Redis
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_assistant_proto_depIdxs = []int32{
	1,  // 0: ingate.assistant.conf.Bootstrap.server:type_name -> ingate.assistant.conf.Server
	2,  // 1: ingate.assistant.conf.Bootstrap.data:type_name -> ingate.assistant.conf.Data
	3,  // 2: ingate.assistant.conf.Bootstrap.model:type_name -> ingate.assistant.conf.Model
	4,  // 3: ingate.assistant.conf.Bootstrap.stream:type_name -> ingate.assistant.conf.Stream
	5,  // 4: ingate.assistant.conf.Bootstrap.logging:type_name -> ingate.assistant.conf.Logging
	6,  // 5: ingate.assistant.conf.Server.http:type_name -> ingate.assistant.conf.Server.HTTP
	9,  // 6: ingate.assistant.conf.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	7,  // 7: ingate.assistant.conf.Data.mysql:type_name -> ingate.assistant.conf.Data.MySQL
	8,  // 8: ingate.assistant.conf.Data.redis:type_name -> ingate.assistant.conf.Data.Redis
	9,  // 9: ingate.assistant.conf.Model.timeout:type_name -> google.protobuf.Duration
	9,  // 10: ingate.assistant.conf.Stream.retention:type_name -> google.protobuf.Duration
	9,  // 11: ingate.assistant.conf.Stream.read_block:type_name -> google.protobuf.Duration
	9,  // 12: ingate.assistant.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	9,  // 13: ingate.assistant.conf.Data.MySQL.dial_timeout:type_name -> google.protobuf.Duration
	9,  // 14: ingate.assistant.conf.Data.MySQL.connection_max_lifetime:type_name -> google.protobuf.Duration
	9,  // 15: ingate.assistant.conf.Data.Redis.dial_timeout:type_name -> google.protobuf.Duration
	9,  // 16: ingate.assistant.conf.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	9,  // 17: ingate.assistant.conf.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_assistant_proto_init() }
func file_assistant_proto_init() {
	if File_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_assistant_proto_goTypes,
		DependencyIndexes: file_assistant_proto_depIdxs,
		MessageInfos:      file_assistant_proto_msgTypes,
	}.Build()
	File_assistant_proto = out.File
	file_assistant_proto_goTypes = nil
	file_assistant_proto_depIdxs = nil
}
