// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const allocateMessageSequence = `-- name: AllocateMessageSequence :execresult
UPDATE assistant_conversations
SET next_message_sequence = LAST_INSERT_ID(next_message_sequence + 1),
    version = version + 1,
    updated_at = ?
WHERE id = ? AND actor_id = ?
`

type AllocateMessageSequenceParams struct {
	UpdatedAt time.Time
	ID        string
	ActorID   string
}

func (q *Queries) AllocateMessageSequence(ctx context.Context, arg AllocateMessageSequenceParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, allocateMessageSequence, arg.UpdatedAt, arg.ID, arg.ActorID)
}

const completeExecution = `-- name: CompleteExecution :execrows
UPDATE assistant_executions
SET state = 'succeeded', assistant_message_id = ?, finished_at = ?
WHERE id = ? AND state = 'running'
`

type CompleteExecutionParams struct {
	AssistantMessageID sql.NullString
	FinishedAt         sql.NullTime
	ID                 string
}

func (q *Queries) CompleteExecution(ctx context.Context, arg CompleteExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExecution, arg.AssistantMessageID, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countRunningExecutions = `-- name: CountRunningExecutions :one
SELECT COUNT(*)
FROM assistant_executions
WHERE conversation_id = ? AND state = 'running'
`

func (q *Queries) CountRunningExecutions(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunningExecutions, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO assistant_conversations (
    id, actor_id, title, version, next_message_sequence, created_at, updated_at
) VALUES (?, ?, ?, 1, 1, ?, ?)
`

type CreateConversationParams struct {
	ID        string
	ActorID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.ActorID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createExecution = `-- name: CreateExecution :exec
INSERT INTO assistant_executions (
    id, conversation_id, user_message_id, state, model, failure_code, started_at
) VALUES (?, ?, ?, ?, ?, '', ?)
`

type CreateExecutionParams struct {
	ID             string
	ConversationID string
	UserMessageID  string
	State          string
	Model          string
	StartedAt      time.Time
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.ExecContext(ctx, createExecution,
		arg.ID,
		arg.ConversationID,
		arg.UserMessageID,
		arg.State,
		arg.Model,
		arg.StartedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO assistant_messages (
    id, conversation_id, sequence, role, content, created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	Sequence       uint64
	Role           string
	Content        string
	CreatedAt      time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.Sequence,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM assistant_conversations
WHERE id = ? AND actor_id = ? AND version = ?
`

type DeleteConversationParams struct {
	ID      string
	ActorID string
	Version uint64
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversation, arg.ID, arg.ActorID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExecution = `-- name: FailExecution :execrows
UPDATE assistant_executions
SET state = 'failed', failure_code = ?, finished_at = ?
WHERE id = ? AND state = 'running'
`

type FailExecutionParams struct {
	FailureCode string
	FinishedAt  sql.NullTime
	ID          string
}

func (q *Queries) FailExecution(ctx context.Context, arg FailExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExecution, arg.FailureCode, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConversation = `-- name: GetConversation :one
SELECT id, actor_id, title, version, next_message_sequence, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
`

type GetConversationParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.Version,
		&i.NextMessageSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, actor_id, title, version, next_message_sequence, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
FOR UPDATE
`

type GetConversationForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversationForUpdate(ctx context.Context, arg GetConversationForUpdateParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationForUpdate, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.Version,
		&i.NextMessageSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT e.id, e.conversation_id, e.user_message_id, e.assistant_message_id, e.state, e.model,
       e.failure_code, e.started_at, e.finished_at
FROM assistant_executions AS e
JOIN assistant_conversations AS c ON c.id = e.conversation_id
WHERE e.id = ? AND c.actor_id = ?
`

type GetExecutionParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (AssistantExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, arg.ID, arg.ActorID)
	var i AssistantExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.State,
		&i.Model,
		&i.FailureCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getExecutionForUpdate = `-- name: GetExecutionForUpdate :one
SELECT e.id, e.conversation_id, e.user_message_id, e.assistant_message_id, e.state, e.model,
       e.failure_code, e.started_at, e.finished_at
FROM assistant_executions AS e
JOIN assistant_conversations AS c ON c.id = e.conversation_id
WHERE e.id = ? AND c.actor_id = ?
FOR UPDATE
`

type GetExecutionForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetExecutionForUpdate(ctx context.Context, arg GetExecutionForUpdateParams) (AssistantExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecutionForUpdate, arg.ID, arg.ActorID)
	var i AssistantExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.State,
		&i.Model,
		&i.FailureCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, actor_id, title, version, next_message_sequence, created_at, updated_at
FROM assistant_conversations
WHERE actor_id = ?
  AND (updated_at < ? OR (updated_at = ? AND id < ?))
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListConversationsParams struct {
	ActorID     string
	UpdatedAt   time.Time
	UpdatedAt_2 time.Time
	ID          string
	Limit       int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]AssistantConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations,
		arg.ActorID,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantConversation{}
	for rows.Next() {
		var i AssistantConversation
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Title,
			&i.Version,
			&i.NextMessageSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sequence, role, content, created_at
FROM assistant_messages
WHERE conversation_id = ? AND sequence > ?
ORDER BY sequence ASC
LIMIT ?
`

type ListMessagesParams struct {
	ConversationID string
	Sequence       uint64
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Sequence,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
