// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelQueuedRun = `-- name: CancelQueuedRun :execrows
UPDATE assistant_runs
SET state = 5, finished_at = ?
WHERE id = ? AND state = 1
`

type CancelQueuedRunParams struct {
	FinishedAt sql.NullTime
	ID         string
}

func (q *Queries) CancelQueuedRun(ctx context.Context, arg CancelQueuedRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedRun, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimNextRun = `-- name: ClaimNextRun :one
SELECT r.id, r.conversation_id, c.actor_id, r.created_at
FROM assistant_runs AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.state = 1
ORDER BY r.created_at ASC, r.id ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimNextRunRow struct {
	ID             string
	ConversationID string
	ActorID        string
	CreatedAt      time.Time
}

func (q *Queries) ClaimNextRun(ctx context.Context) (ClaimNextRunRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextRun)
	var i ClaimNextRunRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const completeRun = `-- name: CompleteRun :execrows
UPDATE assistant_runs
SET state = 3, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type CompleteRunParams struct {
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeRun, arg.FinishedAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveRuns = `-- name: CountActiveRuns :one
SELECT COUNT(*)
FROM assistant_runs
WHERE conversation_id = ? AND state IN (1, 2)
`

func (q *Queries) CountActiveRuns(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRuns, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO assistant_conversations (
    id, actor_id, title, created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID        string
	ActorID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.ActorID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO assistant_messages (
    id, conversation_id, run_id, role, content, reasoning_content, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID               string
	ConversationID   string
	RunID            string
	Role             uint8
	Content          string
	ReasoningContent string
	CreatedAt        time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.RunID,
		arg.Role,
		arg.Content,
		arg.ReasoningContent,
		arg.CreatedAt,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO assistant_runs (
    id, conversation_id, state, created_at
) VALUES (?, ?, 1, ?)
`

type CreateRunParams struct {
	ID             string
	ConversationID string
	CreatedAt      time.Time
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun, arg.ID, arg.ConversationID, arg.CreatedAt)
	return err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM assistant_conversations
WHERE id = ? AND actor_id = ?
`

type DeleteConversationParams struct {
	ID      string
	ActorID string
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversation, arg.ID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM assistant_messages
WHERE conversation_id = ?
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const deleteRunsByConversation = `-- name: DeleteRunsByConversation :exec
DELETE FROM assistant_runs
WHERE conversation_id = ?
`

func (q *Queries) DeleteRunsByConversation(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteRunsByConversation, conversationID)
	return err
}

const failExpiredRuns = `-- name: FailExpiredRuns :execrows
UPDATE assistant_runs
SET state = 4, error_code = ?, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE state = 2 AND lease_expires_at < ?
`

type FailExpiredRunsParams struct {
	ErrorCode      string
	FinishedAt     sql.NullTime
	LeaseExpiresAt sql.NullTime
}

func (q *Queries) FailExpiredRuns(ctx context.Context, arg FailExpiredRunsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredRuns, arg.ErrorCode, arg.FinishedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failRun = `-- name: FailRun :execrows
UPDATE assistant_runs
SET state = 4, error_code = ?, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type FailRunParams struct {
	ErrorCode  string
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) FailRun(ctx context.Context, arg FailRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failRun,
		arg.ErrorCode,
		arg.FinishedAt,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const finishRunCancellation = `-- name: FinishRunCancellation :execrows
UPDATE assistant_runs
SET state = 5, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ? AND cancellation_requested = TRUE
`

type FinishRunCancellationParams struct {
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) FinishRunCancellation(ctx context.Context, arg FinishRunCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishRunCancellation, arg.FinishedAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAssistantModelConnection = `-- name: GetAssistantModelConnection :one
SELECT singleton_id, connection_mode, protocol, endpoint, api_key, model,
       timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
FROM assistant_model_connections
WHERE singleton_id = 1
`

func (q *Queries) GetAssistantModelConnection(ctx context.Context) (AssistantModelConnection, error) {
	row := q.db.QueryRowContext(ctx, getAssistantModelConnection)
	var i AssistantModelConnection
	err := row.Scan(
		&i.SingletonID,
		&i.ConnectionMode,
		&i.Protocol,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.TimeoutMs,
		&i.MaxOutputTokens,
		&i.ReasoningBudgetTokens,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistantModelConnectionForUpdate = `-- name: GetAssistantModelConnectionForUpdate :one
SELECT singleton_id, connection_mode, protocol, endpoint, api_key, model,
       timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
FROM assistant_model_connections
WHERE singleton_id = 1
FOR UPDATE
`

func (q *Queries) GetAssistantModelConnectionForUpdate(ctx context.Context) (AssistantModelConnection, error) {
	row := q.db.QueryRowContext(ctx, getAssistantModelConnectionForUpdate)
	var i AssistantModelConnection
	err := row.Scan(
		&i.SingletonID,
		&i.ConnectionMode,
		&i.Protocol,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.TimeoutMs,
		&i.MaxOutputTokens,
		&i.ReasoningBudgetTokens,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
`

type GetConversationParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
FOR UPDATE
`

type GetConversationForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversationForUpdate(ctx context.Context, arg GetConversationForUpdateParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationForUpdate, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT r.id, r.conversation_id, r.state, r.model, r.error_code,
       r.cancellation_requested, r.worker_id, r.lease_expires_at,
       r.created_at, r.started_at, r.finished_at
FROM assistant_runs AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.id = ? AND c.actor_id = ?
`

type GetRunParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetRun(ctx context.Context, arg GetRunParams) (AssistantRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, arg.ID, arg.ActorID)
	var i AssistantRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.State,
		&i.Model,
		&i.ErrorCode,
		&i.CancellationRequested,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunForUpdate = `-- name: GetRunForUpdate :one
SELECT r.id, r.conversation_id, r.state, r.model, r.error_code,
       r.cancellation_requested, r.worker_id, r.lease_expires_at,
       r.created_at, r.started_at, r.finished_at
FROM assistant_runs AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.id = ? AND c.actor_id = ?
FOR UPDATE
`

type GetRunForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetRunForUpdate(ctx context.Context, arg GetRunForUpdateParams) (AssistantRun, error) {
	row := q.db.QueryRowContext(ctx, getRunForUpdate, arg.ID, arg.ActorID)
	var i AssistantRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.State,
		&i.Model,
		&i.ErrorCode,
		&i.CancellationRequested,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE actor_id = ?
  AND (updated_at < ? OR (updated_at = ? AND id < ?))
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListConversationsParams struct {
	ActorID     string
	UpdatedAt   time.Time
	UpdatedAt_2 time.Time
	ID          string
	Limit       int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]AssistantConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations,
		arg.ActorID,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantConversation{}
	for rows.Next() {
		var i AssistantConversation
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, run_id, role, content, reasoning_content, created_at
FROM assistant_messages
WHERE conversation_id = ?
  AND (created_at > ? OR (created_at = ? AND id > ?))
ORDER BY created_at ASC, id ASC
LIMIT ?
`

type ListMessagesParams struct {
	ConversationID string
	CreatedAt      time.Time
	CreatedAt_2    time.Time
	ID             string
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.ConversationID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Content,
			&i.ReasoningContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, run_id, role, content, reasoning_content, created_at
FROM assistant_messages
WHERE conversation_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListRecentMessagesParams struct {
	ConversationID string
	Limit          int32
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RunID,
			&i.Role,
			&i.Content,
			&i.ReasoningContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewRunLease = `-- name: RenewRunLease :execrows
UPDATE assistant_runs
SET lease_expires_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type RenewRunLeaseParams struct {
	LeaseExpiresAt sql.NullTime
	ID             string
	WorkerID       string
}

func (q *Queries) RenewRunLease(ctx context.Context, arg RenewRunLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewRunLease, arg.LeaseExpiresAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestRunCancellation = `-- name: RequestRunCancellation :execrows
UPDATE assistant_runs
SET cancellation_requested = TRUE
WHERE id = ? AND state = 2
`

func (q *Queries) RequestRunCancellation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestRunCancellation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const runCancellationRequested = `-- name: RunCancellationRequested :one
SELECT cancellation_requested
FROM assistant_runs
WHERE id = ? AND state = 2 AND worker_id = ?
`

type RunCancellationRequestedParams struct {
	ID       string
	WorkerID string
}

func (q *Queries) RunCancellationRequested(ctx context.Context, arg RunCancellationRequestedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, runCancellationRequested, arg.ID, arg.WorkerID)
	var cancellation_requested bool
	err := row.Scan(&cancellation_requested)
	return cancellation_requested, err
}

const setRunModel = `-- name: SetRunModel :execrows
UPDATE assistant_runs
SET model = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type SetRunModelParams struct {
	Model    string
	ID       string
	WorkerID string
}

func (q *Queries) SetRunModel(ctx context.Context, arg SetRunModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunModel, arg.Model, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startRun = `-- name: StartRun :execrows
UPDATE assistant_runs
SET state = 2, worker_id = ?, lease_expires_at = ?, started_at = ?
WHERE id = ? AND state = 1
`

type StartRunParams struct {
	WorkerID       string
	LeaseExpiresAt sql.NullTime
	StartedAt      sql.NullTime
	ID             string
}

func (q *Queries) StartRun(ctx context.Context, arg StartRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startRun,
		arg.WorkerID,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE assistant_conversations
SET updated_at = ?
WHERE id = ? AND actor_id = ?
`

type TouchConversationParams struct {
	UpdatedAt time.Time
	ID        string
	ActorID   string
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchConversation, arg.UpdatedAt, arg.ID, arg.ActorID)
	return err
}

const upsertAssistantModelConnection = `-- name: UpsertAssistantModelConnection :exec
INSERT INTO assistant_model_connections (
    singleton_id, connection_mode, protocol, endpoint, api_key, model,
    timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    connection_mode = VALUES(connection_mode),
    protocol = VALUES(protocol),
    endpoint = VALUES(endpoint),
    api_key = VALUES(api_key),
    model = VALUES(model),
    timeout_ms = VALUES(timeout_ms),
    max_output_tokens = VALUES(max_output_tokens),
    reasoning_budget_tokens = VALUES(reasoning_budget_tokens),
    updated_at = VALUES(updated_at)
`

type UpsertAssistantModelConnectionParams struct {
	ConnectionMode        uint8
	Protocol              uint8
	Endpoint              string
	ApiKey                string
	Model                 string
	TimeoutMs             uint32
	MaxOutputTokens       uint32
	ReasoningBudgetTokens uint32
	UpdatedAt             time.Time
}

func (q *Queries) UpsertAssistantModelConnection(ctx context.Context, arg UpsertAssistantModelConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssistantModelConnection,
		arg.ConnectionMode,
		arg.Protocol,
		arg.Endpoint,
		arg.ApiKey,
		arg.Model,
		arg.TimeoutMs,
		arg.MaxOutputTokens,
		arg.ReasoningBudgetTokens,
		arg.UpdatedAt,
	)
	return err
}
