// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const cancelQueuedExecution = `-- name: CancelQueuedExecution :execrows
UPDATE assistant_agent_executions
SET state = 5, finished_at = ?
WHERE id = ? AND state = 1
`

type CancelQueuedExecutionParams struct {
	FinishedAt sql.NullTime
	ID         string
}

func (q *Queries) CancelQueuedExecution(ctx context.Context, arg CancelQueuedExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelQueuedExecution, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const cancelRunningExecutionSteps = `-- name: CancelRunningExecutionSteps :exec
UPDATE assistant_agent_execution_steps
SET state = 4, finished_at = ?
WHERE execution_id = ? AND state = 1
`

type CancelRunningExecutionStepsParams struct {
	FinishedAt  sql.NullTime
	ExecutionID string
}

func (q *Queries) CancelRunningExecutionSteps(ctx context.Context, arg CancelRunningExecutionStepsParams) error {
	_, err := q.db.ExecContext(ctx, cancelRunningExecutionSteps, arg.FinishedAt, arg.ExecutionID)
	return err
}

const claimNextExecution = `-- name: ClaimNextExecution :one
SELECT r.id, r.conversation_id, c.actor_id, r.created_at
FROM assistant_agent_executions AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.state = 1
ORDER BY r.created_at ASC, r.id ASC
LIMIT 1
FOR UPDATE SKIP LOCKED
`

type ClaimNextExecutionRow struct {
	ID             string
	ConversationID string
	ActorID        string
	CreatedAt      time.Time
}

func (q *Queries) ClaimNextExecution(ctx context.Context) (ClaimNextExecutionRow, error) {
	row := q.db.QueryRowContext(ctx, claimNextExecution)
	var i ClaimNextExecutionRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const completeExecution = `-- name: CompleteExecution :execrows
UPDATE assistant_agent_executions
SET state = 3, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type CompleteExecutionParams struct {
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) CompleteExecution(ctx context.Context, arg CompleteExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExecution, arg.FinishedAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeExecutionStep = `-- name: CompleteExecutionStep :execrows
UPDATE assistant_agent_execution_steps AS i
JOIN assistant_agent_executions AS r ON r.id = i.execution_id
SET i.state = 2, i.summary = ?, i.finished_at = ?
WHERE i.execution_id = ? AND i.call_id = ? AND i.kind = ? AND i.state = 1
  AND r.state = 2 AND r.worker_id = ?
`

type CompleteExecutionStepParams struct {
	Summary     string
	FinishedAt  sql.NullTime
	ExecutionID string
	CallID      string
	Kind        uint8
	WorkerID    string
}

func (q *Queries) CompleteExecutionStep(ctx context.Context, arg CompleteExecutionStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExecutionStep,
		arg.Summary,
		arg.FinishedAt,
		arg.ExecutionID,
		arg.CallID,
		arg.Kind,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveExecutions = `-- name: CountActiveExecutions :one
SELECT COUNT(*)
FROM assistant_agent_executions
WHERE conversation_id = ? AND state IN (1, 2)
`

func (q *Queries) CountActiveExecutions(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveExecutions, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO assistant_conversations (
    id, actor_id, title, created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID        string
	ActorID   string
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.ActorID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createExecution = `-- name: CreateExecution :exec
INSERT INTO assistant_agent_executions (
    id, conversation_id, state, created_at
) VALUES (?, ?, 1, ?)
`

type CreateExecutionParams struct {
	ID             string
	ConversationID string
	CreatedAt      time.Time
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) error {
	_, err := q.db.ExecContext(ctx, createExecution, arg.ID, arg.ConversationID, arg.CreatedAt)
	return err
}

const createExecutionStep = `-- name: CreateExecutionStep :exec
INSERT INTO assistant_agent_execution_steps (
    id, execution_id, sequence, kind, state, name, call_id, summary,
    error_code, created_at, started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateExecutionStepParams struct {
	ID          string
	ExecutionID string
	Sequence    uint32
	Kind        uint8
	State       uint8
	Name        string
	CallID      string
	Summary     string
	ErrorCode   string
	CreatedAt   time.Time
	StartedAt   time.Time
	FinishedAt  sql.NullTime
}

func (q *Queries) CreateExecutionStep(ctx context.Context, arg CreateExecutionStepParams) error {
	_, err := q.db.ExecContext(ctx, createExecutionStep,
		arg.ID,
		arg.ExecutionID,
		arg.Sequence,
		arg.Kind,
		arg.State,
		arg.Name,
		arg.CallID,
		arg.Summary,
		arg.ErrorCode,
		arg.CreatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO assistant_messages (
    id, conversation_id, execution_id, role, content, reasoning_content, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID               string
	ConversationID   string
	ExecutionID      string
	Role             uint8
	Content          string
	ReasoningContent string
	CreatedAt        time.Time
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.ExecutionID,
		arg.Role,
		arg.Content,
		arg.ReasoningContent,
		arg.CreatedAt,
	)
	return err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM assistant_conversations
WHERE id = ? AND actor_id = ?
`

type DeleteConversationParams struct {
	ID      string
	ActorID string
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversation, arg.ID, arg.ActorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExecutionStepsByConversation = `-- name: DeleteExecutionStepsByConversation :exec
DELETE i
FROM assistant_agent_execution_steps AS i
JOIN assistant_agent_executions AS e ON e.id = i.execution_id
WHERE e.conversation_id = ?
`

func (q *Queries) DeleteExecutionStepsByConversation(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionStepsByConversation, conversationID)
	return err
}

const deleteExecutionsByConversation = `-- name: DeleteExecutionsByConversation :exec
DELETE FROM assistant_agent_executions
WHERE conversation_id = ?
`

func (q *Queries) DeleteExecutionsByConversation(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionsByConversation, conversationID)
	return err
}

const deleteMessagesByConversation = `-- name: DeleteMessagesByConversation :exec
DELETE FROM assistant_messages
WHERE conversation_id = ?
`

func (q *Queries) DeleteMessagesByConversation(ctx context.Context, conversationID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesByConversation, conversationID)
	return err
}

const executionCancellationRequested = `-- name: ExecutionCancellationRequested :one
SELECT cancellation_requested
FROM assistant_agent_executions
WHERE id = ? AND state = 2 AND worker_id = ?
`

type ExecutionCancellationRequestedParams struct {
	ID       string
	WorkerID string
}

func (q *Queries) ExecutionCancellationRequested(ctx context.Context, arg ExecutionCancellationRequestedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, executionCancellationRequested, arg.ID, arg.WorkerID)
	var cancellation_requested bool
	err := row.Scan(&cancellation_requested)
	return cancellation_requested, err
}

const failExecution = `-- name: FailExecution :execrows
UPDATE assistant_agent_executions
SET state = 4, error_code = ?, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type FailExecutionParams struct {
	ErrorCode  string
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) FailExecution(ctx context.Context, arg FailExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExecution,
		arg.ErrorCode,
		arg.FinishedAt,
		arg.ID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExecutionStep = `-- name: FailExecutionStep :execrows
UPDATE assistant_agent_execution_steps AS i
JOIN assistant_agent_executions AS r ON r.id = i.execution_id
SET i.state = 3, i.error_code = ?, i.finished_at = ?
WHERE i.execution_id = ? AND i.call_id = ? AND i.kind = ? AND i.state = 1
  AND r.state = 2 AND r.worker_id = ?
`

type FailExecutionStepParams struct {
	ErrorCode   string
	FinishedAt  sql.NullTime
	ExecutionID string
	CallID      string
	Kind        uint8
	WorkerID    string
}

func (q *Queries) FailExecutionStep(ctx context.Context, arg FailExecutionStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExecutionStep,
		arg.ErrorCode,
		arg.FinishedAt,
		arg.ExecutionID,
		arg.CallID,
		arg.Kind,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExpiredExecutionSteps = `-- name: FailExpiredExecutionSteps :exec
UPDATE assistant_agent_execution_steps AS i
JOIN assistant_agent_executions AS r ON r.id = i.execution_id
SET i.state = 3, i.error_code = ?, i.finished_at = ?
WHERE i.state = 1 AND r.state = 2 AND r.lease_expires_at < ?
`

type FailExpiredExecutionStepsParams struct {
	ErrorCode      string
	FinishedAt     sql.NullTime
	LeaseExpiresAt sql.NullTime
}

func (q *Queries) FailExpiredExecutionSteps(ctx context.Context, arg FailExpiredExecutionStepsParams) error {
	_, err := q.db.ExecContext(ctx, failExpiredExecutionSteps, arg.ErrorCode, arg.FinishedAt, arg.LeaseExpiresAt)
	return err
}

const failExpiredExecutions = `-- name: FailExpiredExecutions :execrows
UPDATE assistant_agent_executions
SET state = 4, error_code = ?, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE state = 2 AND lease_expires_at < ?
`

type FailExpiredExecutionsParams struct {
	ErrorCode      string
	FinishedAt     sql.NullTime
	LeaseExpiresAt sql.NullTime
}

func (q *Queries) FailExpiredExecutions(ctx context.Context, arg FailExpiredExecutionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExpiredExecutions, arg.ErrorCode, arg.FinishedAt, arg.LeaseExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failRunningExecutionSteps = `-- name: FailRunningExecutionSteps :exec
UPDATE assistant_agent_execution_steps
SET state = 3, error_code = ?, finished_at = ?
WHERE execution_id = ? AND state = 1
`

type FailRunningExecutionStepsParams struct {
	ErrorCode   string
	FinishedAt  sql.NullTime
	ExecutionID string
}

func (q *Queries) FailRunningExecutionSteps(ctx context.Context, arg FailRunningExecutionStepsParams) error {
	_, err := q.db.ExecContext(ctx, failRunningExecutionSteps, arg.ErrorCode, arg.FinishedAt, arg.ExecutionID)
	return err
}

const finishExecutionCancellation = `-- name: FinishExecutionCancellation :execrows
UPDATE assistant_agent_executions
SET state = 5, worker_id = '', lease_expires_at = NULL, finished_at = ?
WHERE id = ? AND state = 2 AND worker_id = ? AND cancellation_requested = TRUE
`

type FinishExecutionCancellationParams struct {
	FinishedAt sql.NullTime
	ID         string
	WorkerID   string
}

func (q *Queries) FinishExecutionCancellation(ctx context.Context, arg FinishExecutionCancellationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, finishExecutionCancellation, arg.FinishedAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAssistantModelConnection = `-- name: GetAssistantModelConnection :one
SELECT singleton_id, connection_mode, protocol, endpoint, api_key, model,
       timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
FROM assistant_model_connections
WHERE singleton_id = 1
`

func (q *Queries) GetAssistantModelConnection(ctx context.Context) (AssistantModelConnection, error) {
	row := q.db.QueryRowContext(ctx, getAssistantModelConnection)
	var i AssistantModelConnection
	err := row.Scan(
		&i.SingletonID,
		&i.ConnectionMode,
		&i.Protocol,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.TimeoutMs,
		&i.MaxOutputTokens,
		&i.ReasoningBudgetTokens,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssistantModelConnectionForUpdate = `-- name: GetAssistantModelConnectionForUpdate :one
SELECT singleton_id, connection_mode, protocol, endpoint, api_key, model,
       timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
FROM assistant_model_connections
WHERE singleton_id = 1
FOR UPDATE
`

func (q *Queries) GetAssistantModelConnectionForUpdate(ctx context.Context) (AssistantModelConnection, error) {
	row := q.db.QueryRowContext(ctx, getAssistantModelConnectionForUpdate)
	var i AssistantModelConnection
	err := row.Scan(
		&i.SingletonID,
		&i.ConnectionMode,
		&i.Protocol,
		&i.Endpoint,
		&i.ApiKey,
		&i.Model,
		&i.TimeoutMs,
		&i.MaxOutputTokens,
		&i.ReasoningBudgetTokens,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
`

type GetConversationParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationForUpdate = `-- name: GetConversationForUpdate :one
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE id = ? AND actor_id = ?
FOR UPDATE
`

type GetConversationForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetConversationForUpdate(ctx context.Context, arg GetConversationForUpdateParams) (AssistantConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationForUpdate, arg.ID, arg.ActorID)
	var i AssistantConversation
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT r.id, r.conversation_id, r.state, r.model, r.error_code,
       r.cancellation_requested, r.worker_id, r.lease_expires_at,
       r.created_at, r.started_at, r.finished_at
FROM assistant_agent_executions AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.id = ? AND c.actor_id = ?
`

type GetExecutionParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetExecution(ctx context.Context, arg GetExecutionParams) (AssistantAgentExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, arg.ID, arg.ActorID)
	var i AssistantAgentExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.State,
		&i.Model,
		&i.ErrorCode,
		&i.CancellationRequested,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getExecutionForUpdate = `-- name: GetExecutionForUpdate :one
SELECT r.id, r.conversation_id, r.state, r.model, r.error_code,
       r.cancellation_requested, r.worker_id, r.lease_expires_at,
       r.created_at, r.started_at, r.finished_at
FROM assistant_agent_executions AS r
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE r.id = ? AND c.actor_id = ?
FOR UPDATE
`

type GetExecutionForUpdateParams struct {
	ID      string
	ActorID string
}

func (q *Queries) GetExecutionForUpdate(ctx context.Context, arg GetExecutionForUpdateParams) (AssistantAgentExecution, error) {
	row := q.db.QueryRowContext(ctx, getExecutionForUpdate, arg.ID, arg.ActorID)
	var i AssistantAgentExecution
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.State,
		&i.Model,
		&i.ErrorCode,
		&i.CancellationRequested,
		&i.WorkerID,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getExecutionForWorkerUpdate = `-- name: GetExecutionForWorkerUpdate :one
SELECT id
FROM assistant_agent_executions
WHERE id = ? AND state = 2 AND worker_id = ?
FOR UPDATE
`

type GetExecutionForWorkerUpdateParams struct {
	ID       string
	WorkerID string
}

func (q *Queries) GetExecutionForWorkerUpdate(ctx context.Context, arg GetExecutionForWorkerUpdateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getExecutionForWorkerUpdate, arg.ID, arg.WorkerID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, actor_id, title, created_at, updated_at
FROM assistant_conversations
WHERE actor_id = ?
  AND (updated_at < ? OR (updated_at = ? AND id < ?))
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListConversationsParams struct {
	ActorID     string
	UpdatedAt   time.Time
	UpdatedAt_2 time.Time
	ID          string
	Limit       int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]AssistantConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversations,
		arg.ActorID,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantConversation{}
	for rows.Next() {
		var i AssistantConversation
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionSteps = `-- name: ListExecutionSteps :many
SELECT i.id, i.execution_id, i.sequence, i.kind, i.state, i.name, i.call_id,
       i.summary, i.error_code, i.created_at, i.started_at, i.finished_at
FROM assistant_agent_execution_steps AS i
JOIN assistant_agent_executions AS r ON r.id = i.execution_id
JOIN assistant_conversations AS c ON c.id = r.conversation_id
WHERE i.execution_id = ? AND c.actor_id = ?
ORDER BY i.sequence ASC
`

type ListExecutionStepsParams struct {
	ExecutionID string
	ActorID     string
}

func (q *Queries) ListExecutionSteps(ctx context.Context, arg ListExecutionStepsParams) ([]AssistantAgentExecutionStep, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionSteps, arg.ExecutionID, arg.ActorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantAgentExecutionStep{}
	for rows.Next() {
		var i AssistantAgentExecutionStep
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.Sequence,
			&i.Kind,
			&i.State,
			&i.Name,
			&i.CallID,
			&i.Summary,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, execution_id, role, content, reasoning_content, created_at
FROM assistant_messages
WHERE conversation_id = ?
  AND (created_at > ? OR (created_at = ? AND id > ?))
ORDER BY created_at ASC, id ASC
LIMIT ?
`

type ListMessagesParams struct {
	ConversationID string
	CreatedAt      time.Time
	CreatedAt_2    time.Time
	ID             string
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.ConversationID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ExecutionID,
			&i.Role,
			&i.Content,
			&i.ReasoningContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, execution_id, role, content, reasoning_content, created_at
FROM assistant_messages
WHERE conversation_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListRecentMessagesParams struct {
	ConversationID string
	Limit          int32
}

func (q *Queries) ListRecentMessages(ctx context.Context, arg ListRecentMessagesParams) ([]AssistantMessage, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistantMessage{}
	for rows.Next() {
		var i AssistantMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ExecutionID,
			&i.Role,
			&i.Content,
			&i.ReasoningContent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextExecutionStepSequence = `-- name: NextExecutionStepSequence :one
SELECT CAST(COALESCE(MAX(sequence), 0) + 1 AS UNSIGNED)
FROM assistant_agent_execution_steps
WHERE execution_id = ?
`

func (q *Queries) NextExecutionStepSequence(ctx context.Context, executionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextExecutionStepSequence, executionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const renewExecutionLease = `-- name: RenewExecutionLease :execrows
UPDATE assistant_agent_executions
SET lease_expires_at = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type RenewExecutionLeaseParams struct {
	LeaseExpiresAt sql.NullTime
	ID             string
	WorkerID       string
}

func (q *Queries) RenewExecutionLease(ctx context.Context, arg RenewExecutionLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewExecutionLease, arg.LeaseExpiresAt, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const requestExecutionCancellation = `-- name: RequestExecutionCancellation :execrows
UPDATE assistant_agent_executions
SET cancellation_requested = TRUE
WHERE id = ? AND state = 2
`

func (q *Queries) RequestExecutionCancellation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, requestExecutionCancellation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setExecutionModel = `-- name: SetExecutionModel :execrows
UPDATE assistant_agent_executions
SET model = ?
WHERE id = ? AND state = 2 AND worker_id = ?
`

type SetExecutionModelParams struct {
	Model    string
	ID       string
	WorkerID string
}

func (q *Queries) SetExecutionModel(ctx context.Context, arg SetExecutionModelParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setExecutionModel, arg.Model, arg.ID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startExecution = `-- name: StartExecution :execrows
UPDATE assistant_agent_executions
SET state = 2, worker_id = ?, lease_expires_at = ?, started_at = ?
WHERE id = ? AND state = 1
`

type StartExecutionParams struct {
	WorkerID       string
	LeaseExpiresAt sql.NullTime
	StartedAt      sql.NullTime
	ID             string
}

func (q *Queries) StartExecution(ctx context.Context, arg StartExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, startExecution,
		arg.WorkerID,
		arg.LeaseExpiresAt,
		arg.StartedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE assistant_conversations
SET updated_at = ?
WHERE id = ? AND actor_id = ?
`

type TouchConversationParams struct {
	UpdatedAt time.Time
	ID        string
	ActorID   string
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.ExecContext(ctx, touchConversation, arg.UpdatedAt, arg.ID, arg.ActorID)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :execrows
UPDATE assistant_conversations
SET title = ?, updated_at = ?
WHERE id = ? AND actor_id = ?
`

type UpdateConversationTitleParams struct {
	Title     string
	UpdatedAt time.Time
	ID        string
	ActorID   string
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConversationTitle,
		arg.Title,
		arg.UpdatedAt,
		arg.ID,
		arg.ActorID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAssistantModelConnection = `-- name: UpsertAssistantModelConnection :exec
INSERT INTO assistant_model_connections (
    singleton_id, connection_mode, protocol, endpoint, api_key, model,
    timeout_ms, max_output_tokens, reasoning_budget_tokens, updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    connection_mode = VALUES(connection_mode),
    protocol = VALUES(protocol),
    endpoint = VALUES(endpoint),
    api_key = VALUES(api_key),
    model = VALUES(model),
    timeout_ms = VALUES(timeout_ms),
    max_output_tokens = VALUES(max_output_tokens),
    reasoning_budget_tokens = VALUES(reasoning_budget_tokens),
    updated_at = VALUES(updated_at)
`

type UpsertAssistantModelConnectionParams struct {
	ConnectionMode        uint8
	Protocol              uint8
	Endpoint              string
	ApiKey                string
	Model                 string
	TimeoutMs             uint32
	MaxOutputTokens       uint32
	ReasoningBudgetTokens uint32
	UpdatedAt             time.Time
}

func (q *Queries) UpsertAssistantModelConnection(ctx context.Context, arg UpsertAssistantModelConnectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertAssistantModelConnection,
		arg.ConnectionMode,
		arg.Protocol,
		arg.Endpoint,
		arg.ApiKey,
		arg.Model,
		arg.TimeoutMs,
		arg.MaxOutputTokens,
		arg.ReasoningBudgetTokens,
		arg.UpdatedAt,
	)
	return err
}
