// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controller.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 定义 ingate-controller 的完整进程配置
type Bootstrap struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server 定义 xDS 和运维 HTTP 的监听与退出行为
	Server *Server `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// data 定义声明式资源 API 连接
	Data *Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// delivery 定义 Envoy 配置发布时序
	Delivery *Delivery `protobuf:"bytes,3,opt,name=delivery,proto3" json:"delivery,omitempty"`
	// resource_watch 定义声明式资源监听行为
	ResourceWatch *ResourceWatch `protobuf:"bytes,4,opt,name=resource_watch,json=resourceWatch,proto3" json:"resource_watch,omitempty"`
	// logging 定义进程日志行为
	Logging       *Logging `protobuf:"bytes,5,opt,name=logging,proto3" json:"logging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *Bootstrap) GetResourceWatch() *ResourceWatch {
	if x != nil {
		return x.ResourceWatch
	}
	return nil
}

func (x *Bootstrap) GetLogging() *Logging {
	if x != nil {
		return x.Logging
	}
	return nil
}

// Server 定义 Controller 的协议入口
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// grpc 暴露 Envoy ADS 服务
	Grpc *Server_GRPC `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	// http 暴露健康检查和就绪检查
	Http *Server_HTTP `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	// shutdown_timeout 是等待 Controller 各执行循环停止的最长时间
	ShutdownTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

// Data 定义 Controller 使用的数据依赖与本地状态
type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// apiserver 提供 Controller 监听和回写的声明式资源
	Apiserver *Data_APIServer `protobuf:"bytes,1,opt,name=apiserver,proto3" json:"apiserver,omitempty"`
	// wasm 拉取、校验并缓存 Envoy 执行的 Wasm 模块
	Wasm          *Data_Wasm `protobuf:"bytes,2,opt,name=wasm,proto3" json:"wasm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetApiserver() *Data_APIServer {
	if x != nil {
		return x.Apiserver
	}
	return nil
}

func (x *Data) GetWasm() *Data_Wasm {
	if x != nil {
		return x.Wasm
	}
	return nil
}

// Delivery 定义 Candidate 配置的确认和回退期限
type Delivery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// candidate_ack_timeout 是 Envoy 首次收到 Candidate 后的 ACK 等待时间
	CandidateAckTimeout *durationpb.Duration `protobuf:"bytes,1,opt,name=candidate_ack_timeout,json=candidateAckTimeout,proto3" json:"candidate_ack_timeout,omitempty"`
	// nack_rollback_timeout 是 NACK 后恢复 Active 配置的最长等待时间
	NackRollbackTimeout *durationpb.Duration `protobuf:"bytes,2,opt,name=nack_rollback_timeout,json=nackRollbackTimeout,proto3" json:"nack_rollback_timeout,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{3}
}

func (x *Delivery) GetCandidateAckTimeout() *durationpb.Duration {
	if x != nil {
		return x.CandidateAckTimeout
	}
	return nil
}

func (x *Delivery) GetNackRollbackTimeout() *durationpb.Duration {
	if x != nil {
		return x.NackRollbackTimeout
	}
	return nil
}

// ResourceWatch 定义 informer 的资源重同步行为
type ResourceWatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resync_period 为零时只响应声明式资源变更事件
	ResyncPeriod  *durationpb.Duration `protobuf:"bytes,1,opt,name=resync_period,json=resyncPeriod,proto3" json:"resync_period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceWatch) Reset() {
	*x = ResourceWatch{}
	mi := &file_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceWatch) ProtoMessage() {}

func (x *ResourceWatch) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceWatch.ProtoReflect.Descriptor instead.
func (*ResourceWatch) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceWatch) GetResyncPeriod() *durationpb.Duration {
	if x != nil {
		return x.ResyncPeriod
	}
	return nil
}

// Logging 定义结构化日志格式与级别
type Logging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// format 支持 json 和 text
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	// level 支持 debug、info、warn 和 error
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// add_source 控制日志是否包含调用位置
	AddSource     bool `protobuf:"varint,3,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logging) Reset() {
	*x = Logging{}
	mi := &file_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logging) ProtoMessage() {}

func (x *Logging) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logging.ProtoReflect.Descriptor instead.
func (*Logging) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{5}
}

func (x *Logging) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Logging) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logging) GetAddSource() bool {
	if x != nil {
		return x.AddSource
	}
	return false
}

type Server_GRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// addr 是 Envoy 连接的 xDS gRPC 监听地址
	Addr          string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type Server_HTTP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// addr 是健康检查的 HTTP 监听地址
	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	// timeout 限制单次运维 HTTP 请求处理时间
	Timeout       *durationpb.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_APIServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// master 覆盖 kubeconfig 中的 API Server 地址
	Master string `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	// kubeconfig 保存声明式资源 API 的连接与认证配置
	Kubeconfig    string `protobuf:"bytes,2,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_APIServer) Reset() {
	*x = Data_APIServer{}
	mi := &file_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_APIServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_APIServer) ProtoMessage() {}

func (x *Data_APIServer) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_APIServer.ProtoReflect.Descriptor instead.
func (*Data_APIServer) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_APIServer) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *Data_APIServer) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

type Data_Wasm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cache_dir 保存 Controller 已校验的 Wasm 模块
	CacheDir string `protobuf:"bytes,1,opt,name=cache_dir,json=cacheDir,proto3" json:"cache_dir,omitempty"`
	// pull_timeout 限制单次 HTTP 或 OCI 拉取耗时
	PullTimeout *durationpb.Duration `protobuf:"bytes,2,opt,name=pull_timeout,json=pullTimeout,proto3" json:"pull_timeout,omitempty"`
	// max_module_bytes 拒绝超过上限的单个 Wasm 模块
	MaxModuleBytes int64 `protobuf:"varint,3,opt,name=max_module_bytes,json=maxModuleBytes,proto3" json:"max_module_bytes,omitempty"`
	// max_cache_bytes 限制 Wasm 磁盘缓存总量
	MaxCacheBytes int64 `protobuf:"varint,4,opt,name=max_cache_bytes,json=maxCacheBytes,proto3" json:"max_cache_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Wasm) Reset() {
	*x = Data_Wasm{}
	mi := &file_controller_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Wasm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Wasm) ProtoMessage() {}

func (x *Data_Wasm) ProtoReflect() protoreflect.Message {
	mi := &file_controller_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Wasm.ProtoReflect.Descriptor instead.
func (*Data_Wasm) Descriptor() ([]byte, []int) {
	return file_controller_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Wasm) GetCacheDir() string {
	if x != nil {
		return x.CacheDir
	}
	return ""
}

func (x *Data_Wasm) GetPullTimeout() *durationpb.Duration {
	if x != nil {
		return x.PullTimeout
	}
	return nil
}

func (x *Data_Wasm) GetMaxModuleBytes() int64 {
	if x != nil {
		return x.MaxModuleBytes
	}
	return 0
}

func (x *Data_Wasm) GetMaxCacheBytes() int64 {
	if x != nil {
		return x.MaxCacheBytes
	}
	return 0
}

var File_controller_proto protoreflect.FileDescriptor

const file_controller_proto_rawDesc = "" +
	"\n" +
	"\x10controller.proto\x12\x16ingate.controller.conf\x1a\x1egoogle/protobuf/duration.proto\"\xbc\x02\n" +
	"\tBootstrap\x126\n" +
	"\x06server\x18\x01 \x01(\v2\x1e.ingate.controller.conf.ServerR\x06server\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.ingate.controller.conf.DataR\x04data\x12<\n" +
	"\bdelivery\x18\x03 \x01(\v2 .ingate.controller.conf.DeliveryR\bdelivery\x12L\n" +
	"\x0eresource_watch\x18\x04 \x01(\v2%.ingate.controller.conf.ResourceWatchR\rresourceWatch\x129\n" +
	"\alogging\x18\x05 \x01(\v2\x1f.ingate.controller.conf.LoggingR\alogging\"\xad\x02\n" +
	"\x06Server\x127\n" +
	"\x04grpc\x18\x01 \x01(\v2#.ingate.controller.conf.Server.GRPCR\x04grpc\x127\n" +
	"\x04http\x18\x02 \x01(\v2#.ingate.controller.conf.Server.HTTPR\x04http\x12D\n" +
	"\x10shutdown_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1a\x1a\n" +
	"\x04GRPC\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x1aO\n" +
	"\x04HTTP\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xfe\x02\n" +
	"\x04Data\x12D\n" +
	"\tapiserver\x18\x01 \x01(\v2&.ingate.controller.conf.Data.APIServerR\tapiserver\x125\n" +
	"\x04wasm\x18\x02 \x01(\v2!.ingate.controller.conf.Data.WasmR\x04wasm\x1aC\n" +
	"\tAPIServer\x12\x16\n" +
	"\x06master\x18\x01 \x01(\tR\x06master\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x02 \x01(\tR\n" +
	"kubeconfig\x1a\xb3\x01\n" +
	"\x04Wasm\x12\x1b\n" +
	"\tcache_dir\x18\x01 \x01(\tR\bcacheDir\x12<\n" +
	"\fpull_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vpullTimeout\x12(\n" +
	"\x10max_module_bytes\x18\x03 \x01(\x03R\x0emaxModuleBytes\x12&\n" +
	"\x0fmax_cache_bytes\x18\x04 \x01(\x03R\rmaxCacheBytes\"\xa8\x01\n" +
	"\bDelivery\x12M\n" +
	"\x15candidate_ack_timeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x13candidateAckTimeout\x12M\n" +
	"\x15nack_rollback_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x13nackRollbackTimeout\"O\n" +
	"\rResourceWatch\x12>\n" +
	"\rresync_period\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\fresyncPeriod\"V\n" +
	"\aLogging\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"add_source\x18\x03 \x01(\bR\taddSourceB8Z6github.com/lgc202/ingate/internal/controller/conf;confb\x06proto3"

var (
	file_controller_proto_rawDescOnce sync.Once
	file_controller_proto_rawDescData []byte
)

func file_controller_proto_rawDescGZIP() []byte {
	file_controller_proto_rawDescOnce.Do(func() {
		file_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)))
	})
	return file_controller_proto_rawDescData
}

var file_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_controller_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: ingate.controller.conf.Bootstrap
	(*Server)(nil),              // 1: ingate.controller.conf.Server
	(*Data)(nil),                // 2: ingate.controller.conf.Data
	(*Delivery)(nil),            // 3: ingate.controller.conf.Delivery
	(*ResourceWatch)(nil),       // 4: ingate.controller.conf.ResourceWatch
	(*Logging)(nil),             // 5: ingate.controller.conf.Logging
	(*Server_GRPC)(nil),         // 6: ingate.controller.conf.Server.GRPC
	(*Server_HTTP)(nil),         // 7: ingate.controller.conf.Server.HTTP
	(*Data_APIServer)(nil),      // 8: ingate.controller.conf.Data.APIServer
	(*Data_Wasm)(nil),           // 9: ingate.controller.conf.Data.Wasm
	(*durationpb.Duration)(nil), // 10: google.protobuf.Duration
}
var file_controller_proto_depIdxs = []int32{
	1,  // 0: ingate.controller.conf.Bootstrap.server:type_name -> ingate.controller.conf.Server
	2,  // 1: ingate.controller.conf.Bootstrap.data:type_name -> ingate.controller.conf.Data
	3,  // 2: ingate.controller.conf.Bootstrap.delivery:type_name -> ingate.controller.conf.Delivery
	4,  // 3: ingate.controller.conf.Bootstrap.resource_watch:type_name -> ingate.controller.conf.ResourceWatch
	5,  // 4: ingate.controller.conf.Bootstrap.logging:type_name -> ingate.controller.conf.Logging
	6,  // 5: ingate.controller.conf.Server.grpc:type_name -> ingate.controller.conf.Server.GRPC
	7,  // 6: ingate.controller.conf.Server.http:type_name -> ingate.controller.conf.Server.HTTP
	10, // 7: ingate.controller.conf.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	8,  // 8: ingate.controller.conf.Data.apiserver:type_name -> ingate.controller.conf.Data.APIServer
	9,  // 9: ingate.controller.conf.Data.wasm:type_name -> ingate.controller.conf.Data.Wasm
	10, // 10: ingate.controller.conf.Delivery.candidate_ack_timeout:type_name -> google.protobuf.Duration
	10, // 11: ingate.controller.conf.Delivery.nack_rollback_timeout:type_name -> google.protobuf.Duration
	10, // 12: ingate.controller.conf.ResourceWatch.resync_period:type_name -> google.protobuf.Duration
	10, // 13: ingate.controller.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	10, // 14: ingate.controller.conf.Data.Wasm.pull_timeout:type_name -> google.protobuf.Duration
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_controller_proto_init() }
func file_controller_proto_init() {
	if File_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controller_proto_rawDesc), len(file_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controller_proto_goTypes,
		DependencyIndexes: file_controller_proto_depIdxs,
		MessageInfos:      file_controller_proto_msgTypes,
	}.Build()
	File_controller_proto = out.File
	file_controller_proto_goTypes = nil
	file_controller_proto_depIdxs = nil
}
