apiVersion: v1
kind: Config
clusters:
  - name: ingate
    cluster:
      server: https://apiserver:18443
      tls-server-name: ingate.local
      certificate-authority: /opt/ingate/apiserver-client/apiserver.crt
contexts:
  - name: ingate
    context:
      cluster: ingate
      user: ingate
current-context: ingate
users:
  - name: ingate
    user: {}
