// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/lgc202/ingate/internal/controller/conf"
	"github.com/lgc202/ingate/internal/controller/server"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data_APIServer *conf.Data_APIServer, delivery *conf.Delivery, resourceWatch *conf.ResourceWatch, logger *slog.Logger, controllerServiceInstanceID serviceInstanceID) (*kratos.App, error) {
	snapshotCache := newSnapshotCache(logger)
	publisher := newXDSPublisher(snapshotCache)
	deliveryDelivery, err := newDelivery(delivery, publisher)
	if err != nil {
		return nil, err
	}
	httpServer := server.NewHTTPServer(confServer, deliveryDelivery)
	service := newXDSService(snapshotCache, deliveryDelivery, logger)
	grpcServer := server.NewGRPCServer(confServer, service)
	versionedInterface, err := newAPIClient(data_APIServer)
	if err != nil {
		return nil, err
	}
	resourceWatcher, err := newResourceWatcher(resourceWatch, versionedInterface)
	if err != nil {
		return nil, err
	}
	writer := newStatusWriter(versionedInterface)
	controller := newController(resourceWatcher, writer, deliveryDelivery, logger)
	app := newKratosApp(logger, confServer, httpServer, grpcServer, deliveryDelivery, controller, controllerServiceInstanceID)
	return app, nil
}
