// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/access_key.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,4,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowedModels []string               `protobuf:"bytes,6,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKey) Reset() {
	*x = AccessKey{}
	mi := &file_admin_v1_access_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKey) ProtoMessage() {}

func (x *AccessKey) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKey.ProtoReflect.Descriptor instead.
func (*AccessKey) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{0}
}

func (x *AccessKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessKey) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AccessKey) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *AccessKey) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AccessKey) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *AccessKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AccessKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *AccessKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AllowedModels []string               `protobuf:"bytes,2,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessKeyRequest) Reset() {
	*x = CreateAccessKeyRequest{}
	mi := &file_admin_v1_access_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessKeyRequest) ProtoMessage() {}

func (x *CreateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessKeyRequest) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *CreateAccessKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UpdateAccessKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AllowedModels []string               `protobuf:"bytes,3,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessKeyRequest) Reset() {
	*x = UpdateAccessKeyRequest{}
	mi := &file_admin_v1_access_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessKeyRequest) ProtoMessage() {}

func (x *UpdateAccessKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessKeyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAccessKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccessKeyRequest) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *UpdateAccessKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ListAccessKeysReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKeys    []*AccessKey           `protobuf:"bytes,1,rep,name=access_keys,json=accessKeys,proto3" json:"access_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessKeysReply) Reset() {
	*x = ListAccessKeysReply{}
	mi := &file_admin_v1_access_key_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessKeysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessKeysReply) ProtoMessage() {}

func (x *ListAccessKeysReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessKeysReply.ProtoReflect.Descriptor instead.
func (*ListAccessKeysReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{3}
}

func (x *ListAccessKeysReply) GetAccessKeys() []*AccessKey {
	if x != nil {
		return x.AccessKeys
	}
	return nil
}

type AccessKeyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     *AccessKey             `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKeyReply) Reset() {
	*x = AccessKeyReply{}
	mi := &file_admin_v1_access_key_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeyReply) ProtoMessage() {}

func (x *AccessKeyReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKeyReply.ProtoReflect.Descriptor instead.
func (*AccessKeyReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{4}
}

func (x *AccessKeyReply) GetAccessKey() *AccessKey {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

type AccessKeySecretReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     *AccessKey             `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessKeySecretReply) Reset() {
	*x = AccessKeySecretReply{}
	mi := &file_admin_v1_access_key_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessKeySecretReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessKeySecretReply) ProtoMessage() {}

func (x *AccessKeySecretReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_key_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessKeySecretReply.ProtoReflect.Descriptor instead.
func (*AccessKeySecretReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_key_proto_rawDescGZIP(), []int{5}
}

func (x *AccessKeySecretReply) GetAccessKey() *AccessKey {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

func (x *AccessKeySecretReply) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_admin_v1_access_key_proto protoreflect.FileDescriptor

const file_admin_v1_access_key_proto_rawDesc = "" +
	"\n" +
	"\x19admin/v1/access_key.proto\x12\x0fingate.admin.v1\x1a\x15admin/v1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x02\n" +
	"\tAccessKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x04 \x01(\tR\x06suffix\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12%\n" +
	"\x0eallowed_models\x18\x06 \x03(\tR\rallowedModels\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\flast_used_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x97\x01\n" +
	"\x16CreateAccessKeyRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\x0eallowed_models\x18\x02 \x03(\tR\rallowedModels\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xb2\x01\n" +
	"\x16UpdateAccessKeyRequest\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xbaH\x06r\x042\x02\\SR\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12%\n" +
	"\x0eallowed_models\x18\x03 \x03(\tR\rallowedModels\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"R\n" +
	"\x13ListAccessKeysReply\x12;\n" +
	"\vaccess_keys\x18\x01 \x03(\v2\x1a.ingate.admin.v1.AccessKeyR\n" +
	"accessKeys\"K\n" +
	"\x0eAccessKeyReply\x129\n" +
	"\n" +
	"access_key\x18\x01 \x01(\v2\x1a.ingate.admin.v1.AccessKeyR\taccessKey\"i\n" +
	"\x14AccessKeySecretReply\x129\n" +
	"\n" +
	"access_key\x18\x01 \x01(\v2\x1a.ingate.admin.v1.AccessKeyR\taccessKey\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret2\x8d\x06\n" +
	"\x10AccessKeyService\x12k\n" +
	"\x0eListAccessKeys\x12\x16.google.protobuf.Empty\x1a$.ingate.admin.v1.ListAccessKeysReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/access-keys\x12\x81\x01\n" +
	"\x0fCreateAccessKey\x12'.ingate.admin.v1.CreateAccessKeyRequest\x1a%.ingate.admin.v1.AccessKeySecretReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/access-keys\x12\x80\x01\n" +
	"\x0fUpdateAccessKey\x12'.ingate.admin.v1.UpdateAccessKeyRequest\x1a\x1f.ingate.admin.v1.AccessKeyReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/access-keys/{id}\x12\x87\x01\n" +
	"\x13SetAccessKeyEnabled\x12\".ingate.admin.v1.SetEnabledRequest\x1a\x1f.ingate.admin.v1.AccessKeyReply\"+\x82\xd3\xe4\x93\x02%:\x01*2 /api/v1/access-keys/{id}/enabled\x12\x83\x01\n" +
	"\x0fRotateAccessKey\x12 .ingate.admin.v1.ResourceRequest\x1a%.ingate.admin.v1.AccessKeySecretReply\"'\x82\xd3\xe4\x93\x02!\"\x1f/api/v1/access-keys/{id}/rotate\x12u\n" +
	"\x0fDeleteAccessKey\x12 .ingate.admin.v1.ResourceRequest\x1a\x1e.ingate.admin.v1.MutationReply\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/access-keys/{id}B*Z(github.com/lgc202/ingate/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_access_key_proto_rawDescOnce sync.Once
	file_admin_v1_access_key_proto_rawDescData []byte
)

func file_admin_v1_access_key_proto_rawDescGZIP() []byte {
	file_admin_v1_access_key_proto_rawDescOnce.Do(func() {
		file_admin_v1_access_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_access_key_proto_rawDesc), len(file_admin_v1_access_key_proto_rawDesc)))
	})
	return file_admin_v1_access_key_proto_rawDescData
}

var file_admin_v1_access_key_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_admin_v1_access_key_proto_goTypes = []any{
	(*AccessKey)(nil),              // 0: ingate.admin.v1.AccessKey
	(*CreateAccessKeyRequest)(nil), // 1: ingate.admin.v1.CreateAccessKeyRequest
	(*UpdateAccessKeyRequest)(nil), // 2: ingate.admin.v1.UpdateAccessKeyRequest
	(*ListAccessKeysReply)(nil),    // 3: ingate.admin.v1.ListAccessKeysReply
	(*AccessKeyReply)(nil),         // 4: ingate.admin.v1.AccessKeyReply
	(*AccessKeySecretReply)(nil),   // 5: ingate.admin.v1.AccessKeySecretReply
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 7: google.protobuf.Empty
	(*SetEnabledRequest)(nil),      // 8: ingate.admin.v1.SetEnabledRequest
	(*ResourceRequest)(nil),        // 9: ingate.admin.v1.ResourceRequest
	(*MutationReply)(nil),          // 10: ingate.admin.v1.MutationReply
}
var file_admin_v1_access_key_proto_depIdxs = []int32{
	6,  // 0: ingate.admin.v1.AccessKey.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 1: ingate.admin.v1.AccessKey.last_used_at:type_name -> google.protobuf.Timestamp
	6,  // 2: ingate.admin.v1.AccessKey.created_at:type_name -> google.protobuf.Timestamp
	6,  // 3: ingate.admin.v1.CreateAccessKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 4: ingate.admin.v1.UpdateAccessKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: ingate.admin.v1.ListAccessKeysReply.access_keys:type_name -> ingate.admin.v1.AccessKey
	0,  // 6: ingate.admin.v1.AccessKeyReply.access_key:type_name -> ingate.admin.v1.AccessKey
	0,  // 7: ingate.admin.v1.AccessKeySecretReply.access_key:type_name -> ingate.admin.v1.AccessKey
	7,  // 8: ingate.admin.v1.AccessKeyService.ListAccessKeys:input_type -> google.protobuf.Empty
	1,  // 9: ingate.admin.v1.AccessKeyService.CreateAccessKey:input_type -> ingate.admin.v1.CreateAccessKeyRequest
	2,  // 10: ingate.admin.v1.AccessKeyService.UpdateAccessKey:input_type -> ingate.admin.v1.UpdateAccessKeyRequest
	8,  // 11: ingate.admin.v1.AccessKeyService.SetAccessKeyEnabled:input_type -> ingate.admin.v1.SetEnabledRequest
	9,  // 12: ingate.admin.v1.AccessKeyService.RotateAccessKey:input_type -> ingate.admin.v1.ResourceRequest
	9,  // 13: ingate.admin.v1.AccessKeyService.DeleteAccessKey:input_type -> ingate.admin.v1.ResourceRequest
	3,  // 14: ingate.admin.v1.AccessKeyService.ListAccessKeys:output_type -> ingate.admin.v1.ListAccessKeysReply
	5,  // 15: ingate.admin.v1.AccessKeyService.CreateAccessKey:output_type -> ingate.admin.v1.AccessKeySecretReply
	4,  // 16: ingate.admin.v1.AccessKeyService.UpdateAccessKey:output_type -> ingate.admin.v1.AccessKeyReply
	4,  // 17: ingate.admin.v1.AccessKeyService.SetAccessKeyEnabled:output_type -> ingate.admin.v1.AccessKeyReply
	5,  // 18: ingate.admin.v1.AccessKeyService.RotateAccessKey:output_type -> ingate.admin.v1.AccessKeySecretReply
	10, // 19: ingate.admin.v1.AccessKeyService.DeleteAccessKey:output_type -> ingate.admin.v1.MutationReply
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_admin_v1_access_key_proto_init() }
func file_admin_v1_access_key_proto_init() {
	if File_admin_v1_access_key_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_access_key_proto_rawDesc), len(file_admin_v1_access_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_access_key_proto_goTypes,
		DependencyIndexes: file_admin_v1_access_key_proto_depIdxs,
		MessageInfos:      file_admin_v1_access_key_proto_msgTypes,
	}.Build()
	File_admin_v1_access_key_proto = out.File
	file_admin_v1_access_key_proto_goTypes = nil
	file_admin_v1_access_key_proto_depIdxs = nil
}
