// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/access_control_policy.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessControlCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessControlCondition) Reset() {
	*x = AccessControlCondition{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlCondition) ProtoMessage() {}

func (x *AccessControlCondition) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControlCondition.ProtoReflect.Descriptor instead.
func (*AccessControlCondition) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{0}
}

func (x *AccessControlCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessControlCondition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessControlCondition) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AccessControlRule struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Action        string                    `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Conditions    []*AccessControlCondition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessControlRule) Reset() {
	*x = AccessControlRule{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlRule) ProtoMessage() {}

func (x *AccessControlRule) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControlRule.ProtoReflect.Descriptor instead.
func (*AccessControlRule) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AccessControlRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessControlRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AccessControlRule) GetConditions() []*AccessControlCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type AccessControlDenyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessControlDenyResponse) Reset() {
	*x = AccessControlDenyResponse{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlDenyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlDenyResponse) ProtoMessage() {}

func (x *AccessControlDenyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControlDenyResponse.ProtoReflect.Descriptor instead.
func (*AccessControlDenyResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{2}
}

func (x *AccessControlDenyResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AccessControlDenyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AccessControlPolicy struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        *ResourceStatus            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                       `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTarget            `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	DefaultAction string                     `protobuf:"bytes,8,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Rules         []*AccessControlRule       `protobuf:"bytes,9,rep,name=rules,proto3" json:"rules,omitempty"`
	Response      *AccessControlDenyResponse `protobuf:"bytes,10,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAt     *timestamppb.Timestamp     `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessControlPolicy) Reset() {
	*x = AccessControlPolicy{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlPolicy) ProtoMessage() {}

func (x *AccessControlPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControlPolicy.ProtoReflect.Descriptor instead.
func (*AccessControlPolicy) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{3}
}

func (x *AccessControlPolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessControlPolicy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AccessControlPolicy) GetStatus() *ResourceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AccessControlPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessControlPolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AccessControlPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AccessControlPolicy) GetTargets() []*PolicyTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AccessControlPolicy) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *AccessControlPolicy) GetRules() []*AccessControlRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AccessControlPolicy) GetResponse() *AccessControlDenyResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AccessControlPolicy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAccessControlPolicyRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                       `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTargetRef         `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	DefaultAction string                     `protobuf:"bytes,5,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Rules         []*AccessControlRule       `protobuf:"bytes,6,rep,name=rules,proto3" json:"rules,omitempty"`
	Response      *AccessControlDenyResponse `protobuf:"bytes,7,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccessControlPolicyRequest) Reset() {
	*x = CreateAccessControlPolicyRequest{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccessControlPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccessControlPolicyRequest) ProtoMessage() {}

func (x *CreateAccessControlPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccessControlPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateAccessControlPolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccessControlPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccessControlPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAccessControlPolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateAccessControlPolicyRequest) GetTargets() []*PolicyTargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CreateAccessControlPolicyRequest) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *CreateAccessControlPolicyRequest) GetRules() []*AccessControlRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *CreateAccessControlPolicyRequest) GetResponse() *AccessControlDenyResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateAccessControlPolicyRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                       `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTargetRef         `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	DefaultAction string                     `protobuf:"bytes,7,opt,name=default_action,json=defaultAction,proto3" json:"default_action,omitempty"`
	Rules         []*AccessControlRule       `protobuf:"bytes,8,rep,name=rules,proto3" json:"rules,omitempty"`
	Response      *AccessControlDenyResponse `protobuf:"bytes,9,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccessControlPolicyRequest) Reset() {
	*x = UpdateAccessControlPolicyRequest{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccessControlPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccessControlPolicyRequest) ProtoMessage() {}

func (x *UpdateAccessControlPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccessControlPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccessControlPolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccessControlPolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccessControlPolicyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateAccessControlPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccessControlPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAccessControlPolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateAccessControlPolicyRequest) GetTargets() []*PolicyTargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *UpdateAccessControlPolicyRequest) GetDefaultAction() string {
	if x != nil {
		return x.DefaultAction
	}
	return ""
}

func (x *UpdateAccessControlPolicyRequest) GetRules() []*AccessControlRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *UpdateAccessControlPolicyRequest) GetResponse() *AccessControlDenyResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListAccessControlPoliciesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*AccessControlPolicy `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccessControlPoliciesReply) Reset() {
	*x = ListAccessControlPoliciesReply{}
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccessControlPoliciesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccessControlPoliciesReply) ProtoMessage() {}

func (x *ListAccessControlPoliciesReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_access_control_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccessControlPoliciesReply.ProtoReflect.Descriptor instead.
func (*ListAccessControlPoliciesReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_access_control_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ListAccessControlPoliciesReply) GetPolicies() []*AccessControlPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_admin_v1_access_control_policy_proto protoreflect.FileDescriptor

const file_admin_v1_access_control_policy_proto_rawDesc = "" +
	"\n" +
	"$admin/v1/access_control_policy.proto\x12\x0fingate.admin.v1\x1a\x15admin/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n" +
	"\x16AccessControlCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x88\x01\n" +
	"\x11AccessControlRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12G\n" +
	"\n" +
	"conditions\x18\x03 \x03(\v2'.ingate.admin.v1.AccessControlConditionR\n" +
	"conditions\"V\n" +
	"\x19AccessControlDenyResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe5\x03\n" +
	"\x13AccessControlPolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x127\n" +
	"\x06status\x18\x03 \x01(\v2\x1f.ingate.admin.v1.ResourceStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x127\n" +
	"\atargets\x18\a \x03(\v2\x1d.ingate.admin.v1.PolicyTargetR\atargets\x12%\n" +
	"\x0edefault_action\x18\b \x01(\tR\rdefaultAction\x128\n" +
	"\x05rules\x18\t \x03(\v2\".ingate.admin.v1.AccessControlRuleR\x05rules\x12F\n" +
	"\bresponse\x18\n" +
	" \x01(\v2*.ingate.admin.v1.AccessControlDenyResponseR\bresponse\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd7\x02\n" +
	" CreateAccessControlPolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12:\n" +
	"\atargets\x18\x04 \x03(\v2 .ingate.admin.v1.PolicyTargetRefR\atargets\x12%\n" +
	"\x0edefault_action\x18\x05 \x01(\tR\rdefaultAction\x128\n" +
	"\x05rules\x18\x06 \x03(\v2\".ingate.admin.v1.AccessControlRuleR\x05rules\x12F\n" +
	"\bresponse\x18\a \x01(\v2*.ingate.admin.v1.AccessControlDenyResponseR\bresponse\"\x81\x03\n" +
	" UpdateAccessControlPolicyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12:\n" +
	"\atargets\x18\x06 \x03(\v2 .ingate.admin.v1.PolicyTargetRefR\atargets\x12%\n" +
	"\x0edefault_action\x18\a \x01(\tR\rdefaultAction\x128\n" +
	"\x05rules\x18\b \x03(\v2\".ingate.admin.v1.AccessControlRuleR\x05rules\x12F\n" +
	"\bresponse\x18\t \x01(\v2*.ingate.admin.v1.AccessControlDenyResponseR\bresponse\"b\n" +
	"\x1eListAccessControlPoliciesReply\x12@\n" +
	"\bpolicies\x18\x01 \x03(\v2$.ingate.admin.v1.AccessControlPolicyR\bpolicies2\xa9\a\n" +
	"\x1aAccessControlPolicyService\x12\x8d\x01\n" +
	"\x19ListAccessControlPolicies\x12\x16.google.protobuf.Empty\x1a/.ingate.admin.v1.ListAccessControlPoliciesReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/access-control-policies\x12\x8e\x01\n" +
	"\x16GetAccessControlPolicy\x12 .ingate.admin.v1.ResourceRequest\x1a$.ingate.admin.v1.AccessControlPolicy\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/access-control-policies/{id}\x12\x9a\x01\n" +
	"\x19CreateAccessControlPolicy\x121.ingate.admin.v1.CreateAccessControlPolicyRequest\x1a\x1e.ingate.admin.v1.MutationReply\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/access-control-policies\x12\x9f\x01\n" +
	"\x19UpdateAccessControlPolicy\x121.ingate.admin.v1.UpdateAccessControlPolicyRequest\x1a\x1e.ingate.admin.v1.MutationReply\"/\x82\xd3\xe4\x93\x02):\x01*\x1a$/api/v1/access-control-policies/{id}\x12\x9c\x01\n" +
	"\x1dSetAccessControlPolicyEnabled\x12\".ingate.admin.v1.SetEnabledRequest\x1a\x1e.ingate.admin.v1.MutationReply\"7\x82\xd3\xe4\x93\x021:\x01*2,/api/v1/access-control-policies/{id}/enabled\x12\x8b\x01\n" +
	"\x19DeleteAccessControlPolicy\x12 .ingate.admin.v1.ResourceRequest\x1a\x1e.ingate.admin.v1.MutationReply\",\x82\xd3\xe4\x93\x02&*$/api/v1/access-control-policies/{id}B*Z(github.com/lgc202/ingate/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_access_control_policy_proto_rawDescOnce sync.Once
	file_admin_v1_access_control_policy_proto_rawDescData []byte
)

func file_admin_v1_access_control_policy_proto_rawDescGZIP() []byte {
	file_admin_v1_access_control_policy_proto_rawDescOnce.Do(func() {
		file_admin_v1_access_control_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_access_control_policy_proto_rawDesc), len(file_admin_v1_access_control_policy_proto_rawDesc)))
	})
	return file_admin_v1_access_control_policy_proto_rawDescData
}

var file_admin_v1_access_control_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_v1_access_control_policy_proto_goTypes = []any{
	(*AccessControlCondition)(nil),           // 0: ingate.admin.v1.AccessControlCondition
	(*AccessControlRule)(nil),                // 1: ingate.admin.v1.AccessControlRule
	(*AccessControlDenyResponse)(nil),        // 2: ingate.admin.v1.AccessControlDenyResponse
	(*AccessControlPolicy)(nil),              // 3: ingate.admin.v1.AccessControlPolicy
	(*CreateAccessControlPolicyRequest)(nil), // 4: ingate.admin.v1.CreateAccessControlPolicyRequest
	(*UpdateAccessControlPolicyRequest)(nil), // 5: ingate.admin.v1.UpdateAccessControlPolicyRequest
	(*ListAccessControlPoliciesReply)(nil),   // 6: ingate.admin.v1.ListAccessControlPoliciesReply
	(*ResourceStatus)(nil),                   // 7: ingate.admin.v1.ResourceStatus
	(*PolicyTarget)(nil),                     // 8: ingate.admin.v1.PolicyTarget
	(*timestamppb.Timestamp)(nil),            // 9: google.protobuf.Timestamp
	(*PolicyTargetRef)(nil),                  // 10: ingate.admin.v1.PolicyTargetRef
	(*emptypb.Empty)(nil),                    // 11: google.protobuf.Empty
	(*ResourceRequest)(nil),                  // 12: ingate.admin.v1.ResourceRequest
	(*SetEnabledRequest)(nil),                // 13: ingate.admin.v1.SetEnabledRequest
	(*MutationReply)(nil),                    // 14: ingate.admin.v1.MutationReply
}
var file_admin_v1_access_control_policy_proto_depIdxs = []int32{
	0,  // 0: ingate.admin.v1.AccessControlRule.conditions:type_name -> ingate.admin.v1.AccessControlCondition
	7,  // 1: ingate.admin.v1.AccessControlPolicy.status:type_name -> ingate.admin.v1.ResourceStatus
	8,  // 2: ingate.admin.v1.AccessControlPolicy.targets:type_name -> ingate.admin.v1.PolicyTarget
	1,  // 3: ingate.admin.v1.AccessControlPolicy.rules:type_name -> ingate.admin.v1.AccessControlRule
	2,  // 4: ingate.admin.v1.AccessControlPolicy.response:type_name -> ingate.admin.v1.AccessControlDenyResponse
	9,  // 5: ingate.admin.v1.AccessControlPolicy.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: ingate.admin.v1.CreateAccessControlPolicyRequest.targets:type_name -> ingate.admin.v1.PolicyTargetRef
	1,  // 7: ingate.admin.v1.CreateAccessControlPolicyRequest.rules:type_name -> ingate.admin.v1.AccessControlRule
	2,  // 8: ingate.admin.v1.CreateAccessControlPolicyRequest.response:type_name -> ingate.admin.v1.AccessControlDenyResponse
	10, // 9: ingate.admin.v1.UpdateAccessControlPolicyRequest.targets:type_name -> ingate.admin.v1.PolicyTargetRef
	1,  // 10: ingate.admin.v1.UpdateAccessControlPolicyRequest.rules:type_name -> ingate.admin.v1.AccessControlRule
	2,  // 11: ingate.admin.v1.UpdateAccessControlPolicyRequest.response:type_name -> ingate.admin.v1.AccessControlDenyResponse
	3,  // 12: ingate.admin.v1.ListAccessControlPoliciesReply.policies:type_name -> ingate.admin.v1.AccessControlPolicy
	11, // 13: ingate.admin.v1.AccessControlPolicyService.ListAccessControlPolicies:input_type -> google.protobuf.Empty
	12, // 14: ingate.admin.v1.AccessControlPolicyService.GetAccessControlPolicy:input_type -> ingate.admin.v1.ResourceRequest
	4,  // 15: ingate.admin.v1.AccessControlPolicyService.CreateAccessControlPolicy:input_type -> ingate.admin.v1.CreateAccessControlPolicyRequest
	5,  // 16: ingate.admin.v1.AccessControlPolicyService.UpdateAccessControlPolicy:input_type -> ingate.admin.v1.UpdateAccessControlPolicyRequest
	13, // 17: ingate.admin.v1.AccessControlPolicyService.SetAccessControlPolicyEnabled:input_type -> ingate.admin.v1.SetEnabledRequest
	12, // 18: ingate.admin.v1.AccessControlPolicyService.DeleteAccessControlPolicy:input_type -> ingate.admin.v1.ResourceRequest
	6,  // 19: ingate.admin.v1.AccessControlPolicyService.ListAccessControlPolicies:output_type -> ingate.admin.v1.ListAccessControlPoliciesReply
	3,  // 20: ingate.admin.v1.AccessControlPolicyService.GetAccessControlPolicy:output_type -> ingate.admin.v1.AccessControlPolicy
	14, // 21: ingate.admin.v1.AccessControlPolicyService.CreateAccessControlPolicy:output_type -> ingate.admin.v1.MutationReply
	14, // 22: ingate.admin.v1.AccessControlPolicyService.UpdateAccessControlPolicy:output_type -> ingate.admin.v1.MutationReply
	14, // 23: ingate.admin.v1.AccessControlPolicyService.SetAccessControlPolicyEnabled:output_type -> ingate.admin.v1.MutationReply
	14, // 24: ingate.admin.v1.AccessControlPolicyService.DeleteAccessControlPolicy:output_type -> ingate.admin.v1.MutationReply
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_admin_v1_access_control_policy_proto_init() }
func file_admin_v1_access_control_policy_proto_init() {
	if File_admin_v1_access_control_policy_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_access_control_policy_proto_rawDesc), len(file_admin_v1_access_control_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_access_control_policy_proto_goTypes,
		DependencyIndexes: file_admin_v1_access_control_policy_proto_depIdxs,
		MessageInfos:      file_admin_v1_access_control_policy_proto_msgTypes,
	}.Build()
	File_admin_v1_access_control_policy_proto = out.File
	file_admin_v1_access_control_policy_proto_goTypes = nil
	file_admin_v1_access_control_policy_proto_depIdxs = nil
}
