// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin/v1/ai_usage.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIUsageService_GetAIUsageAnalysis_FullMethodName = "/ingate.admin.v1.AIUsageService/GetAIUsageAnalysis"
)

// AIUsageServiceClient is the client API for AIUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AIUsageService 提供控制台模型调用与 Token 用量分析。
type AIUsageServiceClient interface {
	// GetAIUsageAnalysis 查询同一范围内的汇总、趋势与排名。
	GetAIUsageAnalysis(ctx context.Context, in *GetAIUsageAnalysisRequest, opts ...grpc.CallOption) (*GetAIUsageAnalysisResponse, error)
}

type aIUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIUsageServiceClient(cc grpc.ClientConnInterface) AIUsageServiceClient {
	return &aIUsageServiceClient{cc}
}

func (c *aIUsageServiceClient) GetAIUsageAnalysis(ctx context.Context, in *GetAIUsageAnalysisRequest, opts ...grpc.CallOption) (*GetAIUsageAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAIUsageAnalysisResponse)
	err := c.cc.Invoke(ctx, AIUsageService_GetAIUsageAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIUsageServiceServer is the server API for AIUsageService service.
// All implementations should embed UnimplementedAIUsageServiceServer
// for forward compatibility.
//
// AIUsageService 提供控制台模型调用与 Token 用量分析。
type AIUsageServiceServer interface {
	// GetAIUsageAnalysis 查询同一范围内的汇总、趋势与排名。
	GetAIUsageAnalysis(context.Context, *GetAIUsageAnalysisRequest) (*GetAIUsageAnalysisResponse, error)
}

// UnimplementedAIUsageServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIUsageServiceServer struct{}

func (UnimplementedAIUsageServiceServer) GetAIUsageAnalysis(context.Context, *GetAIUsageAnalysisRequest) (*GetAIUsageAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAIUsageAnalysis not implemented")
}
func (UnimplementedAIUsageServiceServer) testEmbeddedByValue() {}

// UnsafeAIUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIUsageServiceServer will
// result in compilation errors.
type UnsafeAIUsageServiceServer interface {
	mustEmbedUnimplementedAIUsageServiceServer()
}

func RegisterAIUsageServiceServer(s grpc.ServiceRegistrar, srv AIUsageServiceServer) {
	// If the following call panics, it indicates UnimplementedAIUsageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIUsageService_ServiceDesc, srv)
}

func _AIUsageService_GetAIUsageAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAIUsageAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIUsageServiceServer).GetAIUsageAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIUsageService_GetAIUsageAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIUsageServiceServer).GetAIUsageAnalysis(ctx, req.(*GetAIUsageAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIUsageService_ServiceDesc is the grpc.ServiceDesc for AIUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingate.admin.v1.AIUsageService",
	HandlerType: (*AIUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAIUsageAnalysis",
			Handler:    _AIUsageService_GetAIUsageAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/ai_usage.proto",
}
