// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin/v1/authentication.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthenticationService_GetAuthenticationConfiguration_FullMethodName = "/ingate.admin.v1.AuthenticationService/GetAuthenticationConfiguration"
	AuthenticationService_GetCurrentPrincipal_FullMethodName            = "/ingate.admin.v1.AuthenticationService/GetCurrentPrincipal"
)

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthenticationService 向 Console 提供公开登录参数和当前已验证身份
type AuthenticationServiceClient interface {
	GetAuthenticationConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthenticationConfiguration, error)
	GetCurrentPrincipal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CurrentPrincipal, error)
}

type authenticationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthenticationServiceClient(cc grpc.ClientConnInterface) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) GetAuthenticationConfiguration(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*AuthenticationConfiguration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthenticationConfiguration)
	err := c.cc.Invoke(ctx, AuthenticationService_GetAuthenticationConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetCurrentPrincipal(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CurrentPrincipal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CurrentPrincipal)
	err := c.cc.Invoke(ctx, AuthenticationService_GetCurrentPrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
// All implementations should embed UnimplementedAuthenticationServiceServer
// for forward compatibility.
//
// AuthenticationService 向 Console 提供公开登录参数和当前已验证身份
type AuthenticationServiceServer interface {
	GetAuthenticationConfiguration(context.Context, *emptypb.Empty) (*AuthenticationConfiguration, error)
	GetCurrentPrincipal(context.Context, *emptypb.Empty) (*CurrentPrincipal, error)
}

// UnimplementedAuthenticationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthenticationServiceServer struct{}

func (UnimplementedAuthenticationServiceServer) GetAuthenticationConfiguration(context.Context, *emptypb.Empty) (*AuthenticationConfiguration, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthenticationConfiguration not implemented")
}
func (UnimplementedAuthenticationServiceServer) GetCurrentPrincipal(context.Context, *emptypb.Empty) (*CurrentPrincipal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentPrincipal not implemented")
}
func (UnimplementedAuthenticationServiceServer) testEmbeddedByValue() {}

// UnsafeAuthenticationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthenticationServiceServer will
// result in compilation errors.
type UnsafeAuthenticationServiceServer interface {
	mustEmbedUnimplementedAuthenticationServiceServer()
}

func RegisterAuthenticationServiceServer(s grpc.ServiceRegistrar, srv AuthenticationServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthenticationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthenticationService_ServiceDesc, srv)
}

func _AuthenticationService_GetAuthenticationConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetAuthenticationConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetAuthenticationConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetAuthenticationConfiguration(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetCurrentPrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetCurrentPrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthenticationService_GetCurrentPrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetCurrentPrincipal(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthenticationService_ServiceDesc is the grpc.ServiceDesc for AuthenticationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthenticationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingate.admin.v1.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthenticationConfiguration",
			Handler:    _AuthenticationService_GetAuthenticationConfiguration_Handler,
		},
		{
			MethodName: "GetCurrentPrincipal",
			Handler:    _AuthenticationService_GetCurrentPrincipal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/authentication.proto",
}
