// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/gateway.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayProtocol int32

const (
	GatewayProtocol_GATEWAY_PROTOCOL_UNSPECIFIED GatewayProtocol = 0
	GatewayProtocol_GATEWAY_PROTOCOL_HTTP        GatewayProtocol = 1
	GatewayProtocol_GATEWAY_PROTOCOL_HTTPS       GatewayProtocol = 2
)

// Enum value maps for GatewayProtocol.
var (
	GatewayProtocol_name = map[int32]string{
		0: "GATEWAY_PROTOCOL_UNSPECIFIED",
		1: "GATEWAY_PROTOCOL_HTTP",
		2: "GATEWAY_PROTOCOL_HTTPS",
	}
	GatewayProtocol_value = map[string]int32{
		"GATEWAY_PROTOCOL_UNSPECIFIED": 0,
		"GATEWAY_PROTOCOL_HTTP":        1,
		"GATEWAY_PROTOCOL_HTTPS":       2,
	}
)

func (x GatewayProtocol) Enum() *GatewayProtocol {
	p := new(GatewayProtocol)
	*p = x
	return p
}

func (x GatewayProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GatewayProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (GatewayProtocol) Type() protoreflect.EnumType {
	return &file_admin_v1_gateway_proto_enumTypes[0]
}

func (x GatewayProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GatewayProtocol.Descriptor instead.
func (GatewayProtocol) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type GatewayListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      GatewayProtocol        `protobuf:"varint,2,opt,name=protocol,proto3,enum=ingate.admin.v1.GatewayProtocol" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CertificateId string                 `protobuf:"bytes,5,opt,name=certificate_id,json=certificateID,proto3" json:"certificate_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayListener) Reset() {
	*x = GatewayListener{}
	mi := &file_admin_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayListener) ProtoMessage() {}

func (x *GatewayListener) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayListener.ProtoReflect.Descriptor instead.
func (*GatewayListener) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayListener) GetProtocol() GatewayProtocol {
	if x != nil {
		return x.Protocol
	}
	return GatewayProtocol_GATEWAY_PROTOCOL_UNSPECIFIED
}

func (x *GatewayListener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GatewayListener) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GatewayListener) GetCertificateId() string {
	if x != nil {
		return x.CertificateId
	}
	return ""
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Listeners     []*GatewayListener     `protobuf:"bytes,4,rep,name=listeners,proto3" json:"listeners,omitempty"`
	State         ResourceState          `protobuf:"varint,5,opt,name=state,proto3,enum=ingate.admin.v1.ResourceState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_admin_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *Gateway) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Gateway) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Gateway) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Gateway) GetListeners() []*GatewayListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *Gateway) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *Gateway) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Gateway) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Gateway) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Gateway) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListGatewaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	State         ResourceState          `protobuf:"varint,5,opt,name=state,proto3,enum=ingate.admin.v1.ResourceState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysRequest) Reset() {
	*x = ListGatewaysRequest{}
	mi := &file_admin_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysRequest) ProtoMessage() {}

func (x *ListGatewaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysRequest.ProtoReflect.Descriptor instead.
func (*ListGatewaysRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ListGatewaysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGatewaysRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListGatewaysRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListGatewaysRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *ListGatewaysRequest) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

type ListGatewaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateways      []*Gateway             `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewaysResponse) Reset() {
	*x = ListGatewaysResponse{}
	mi := &file_admin_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewaysResponse) ProtoMessage() {}

func (x *ListGatewaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewaysResponse.ProtoReflect.Descriptor instead.
func (*ListGatewaysResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ListGatewaysResponse) GetGateways() []*Gateway {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *ListGatewaysResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type GetGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayRequest) Reset() {
	*x = GetGatewayRequest{}
	mi := &file_admin_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayRequest) ProtoMessage() {}

func (x *GetGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetGatewayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       *bool                  `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Listeners     []*GatewayListener     `protobuf:"bytes,3,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayRequest) Reset() {
	*x = CreateGatewayRequest{}
	mi := &file_admin_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayRequest) ProtoMessage() {}

func (x *CreateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayRequest.ProtoReflect.Descriptor instead.
func (*CreateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGatewayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGatewayRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *CreateGatewayRequest) GetListeners() []*GatewayListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type UpdateGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       *bool                  `protobuf:"varint,4,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Listeners     []*GatewayListener     `protobuf:"bytes,5,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGatewayRequest) Reset() {
	*x = UpdateGatewayRequest{}
	mi := &file_admin_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGatewayRequest) ProtoMessage() {}

func (x *UpdateGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGatewayRequest.ProtoReflect.Descriptor instead.
func (*UpdateGatewayRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGatewayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGatewayRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateGatewayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGatewayRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *UpdateGatewayRequest) GetListeners() []*GatewayListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type DeleteGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGatewayRequest) Reset() {
	*x = DeleteGatewayRequest{}
	mi := &file_admin_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGatewayRequest) ProtoMessage() {}

func (x *DeleteGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGatewayRequest.ProtoReflect.Descriptor instead.
func (*DeleteGatewayRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGatewayRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteGatewayRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_admin_v1_gateway_proto protoreflect.FileDescriptor

const file_admin_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x16admin/v1/gateway.proto\x12\x0fingate.admin.v1\x1a\x15admin/v1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x0fGatewayListener\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04 \x01(?R\x04name\x12<\n" +
	"\bprotocol\x18\x02 \x01(\x0e2 .ingate.admin.v1.GatewayProtocolR\bprotocol\x12\x1f\n" +
	"\x04port\x18\x03 \x01(\rB\v\xbaH\b*\x06\x18\xff\xff\x03(\x01R\x04port\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12%\n" +
	"\x0ecertificate_id\x18\x05 \x01(\tR\rcertificateID\"\xe7\x02\n" +
	"\aGateway\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12>\n" +
	"\tlisteners\x18\x04 \x03(\v2 .ingate.admin.v1.GatewayListenerR\tlisteners\x124\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1e.ingate.admin.v1.ResourceStateR\x05state\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcd\x01\n" +
	"\x13ListGatewaysRequest\x12\x1d\n" +
	"\x05limit\x18\x01 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1d\n" +
	"\aenabled\x18\x04 \x01(\bH\x00R\aenabled\x88\x01\x01\x12>\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1e.ingate.admin.v1.ResourceStateB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05stateB\n" +
	"\n" +
	"\b_enabled\"m\n" +
	"\x14ListGatewaysResponse\x124\n" +
	"\bgateways\x18\x01 \x03(\v2\x18.ingate.admin.v1.GatewayR\bgateways\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"-\n" +
	"\x11GetGatewayRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"\xb5\x01\n" +
	"\x14CreateGatewayRequest\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05 \x01(\x80\x02R\x04name\x12%\n" +
	"\aenabled\x18\x02 \x01(\bB\x06\xbaH\x03\xc8\x01\x01H\x00R\aenabled\x88\x01\x01\x12J\n" +
	"\tlisteners\x18\x03 \x03(\v2 .ingate.admin.v1.GatewayListenerB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10@R\tlistenersB\n" +
	"\n" +
	"\b_enabled\"\xf2\x01\n" +
	"\x14UpdateGatewayRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\aversion\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aversion\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05 \x01(\x80\x02R\x04name\x12%\n" +
	"\aenabled\x18\x04 \x01(\bB\x06\xbaH\x03\xc8\x01\x01H\x00R\aenabled\x88\x01\x01\x12J\n" +
	"\tlisteners\x18\x05 \x03(\v2 .ingate.admin.v1.GatewayListenerB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10@R\tlistenersB\n" +
	"\n" +
	"\b_enabled\"S\n" +
	"\x14DeleteGatewayRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12!\n" +
	"\aversion\x18\x02 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\aversion*j\n" +
	"\x0fGatewayProtocol\x12 \n" +
	"\x1cGATEWAY_PROTOCOL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15GATEWAY_PROTOCOL_HTTP\x10\x01\x12\x1a\n" +
	"\x16GATEWAY_PROTOCOL_HTTPS\x10\x022\xc4\x04\n" +
	"\x0eGatewayService\x12u\n" +
	"\fListGateways\x12$.ingate.admin.v1.ListGatewaysRequest\x1a%.ingate.admin.v1.ListGatewaysResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/gateways\x12i\n" +
	"\n" +
	"GetGateway\x12\".ingate.admin.v1.GetGatewayRequest\x1a\x18.ingate.admin.v1.Gateway\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/gateways/{id}\x12m\n" +
	"\rCreateGateway\x12%.ingate.admin.v1.CreateGatewayRequest\x1a\x18.ingate.admin.v1.Gateway\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/gateways\x12r\n" +
	"\rUpdateGateway\x12%.ingate.admin.v1.UpdateGatewayRequest\x1a\x18.ingate.admin.v1.Gateway\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/gateways/{id}\x12m\n" +
	"\rDeleteGateway\x12%.ingate.admin.v1.DeleteGatewayRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/gateways/{id}B*Z(github.com/lgc202/ingate/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_gateway_proto_rawDescOnce sync.Once
	file_admin_v1_gateway_proto_rawDescData []byte
)

func file_admin_v1_gateway_proto_rawDescGZIP() []byte {
	file_admin_v1_gateway_proto_rawDescOnce.Do(func() {
		file_admin_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_gateway_proto_rawDesc), len(file_admin_v1_gateway_proto_rawDesc)))
	})
	return file_admin_v1_gateway_proto_rawDescData
}

var file_admin_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_admin_v1_gateway_proto_goTypes = []any{
	(GatewayProtocol)(0),          // 0: ingate.admin.v1.GatewayProtocol
	(*GatewayListener)(nil),       // 1: ingate.admin.v1.GatewayListener
	(*Gateway)(nil),               // 2: ingate.admin.v1.Gateway
	(*ListGatewaysRequest)(nil),   // 3: ingate.admin.v1.ListGatewaysRequest
	(*ListGatewaysResponse)(nil),  // 4: ingate.admin.v1.ListGatewaysResponse
	(*GetGatewayRequest)(nil),     // 5: ingate.admin.v1.GetGatewayRequest
	(*CreateGatewayRequest)(nil),  // 6: ingate.admin.v1.CreateGatewayRequest
	(*UpdateGatewayRequest)(nil),  // 7: ingate.admin.v1.UpdateGatewayRequest
	(*DeleteGatewayRequest)(nil),  // 8: ingate.admin.v1.DeleteGatewayRequest
	(ResourceState)(0),            // 9: ingate.admin.v1.ResourceState
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_admin_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: ingate.admin.v1.GatewayListener.protocol:type_name -> ingate.admin.v1.GatewayProtocol
	1,  // 1: ingate.admin.v1.Gateway.listeners:type_name -> ingate.admin.v1.GatewayListener
	9,  // 2: ingate.admin.v1.Gateway.state:type_name -> ingate.admin.v1.ResourceState
	10, // 3: ingate.admin.v1.Gateway.created_at:type_name -> google.protobuf.Timestamp
	10, // 4: ingate.admin.v1.Gateway.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 5: ingate.admin.v1.ListGatewaysRequest.state:type_name -> ingate.admin.v1.ResourceState
	2,  // 6: ingate.admin.v1.ListGatewaysResponse.gateways:type_name -> ingate.admin.v1.Gateway
	1,  // 7: ingate.admin.v1.CreateGatewayRequest.listeners:type_name -> ingate.admin.v1.GatewayListener
	1,  // 8: ingate.admin.v1.UpdateGatewayRequest.listeners:type_name -> ingate.admin.v1.GatewayListener
	3,  // 9: ingate.admin.v1.GatewayService.ListGateways:input_type -> ingate.admin.v1.ListGatewaysRequest
	5,  // 10: ingate.admin.v1.GatewayService.GetGateway:input_type -> ingate.admin.v1.GetGatewayRequest
	6,  // 11: ingate.admin.v1.GatewayService.CreateGateway:input_type -> ingate.admin.v1.CreateGatewayRequest
	7,  // 12: ingate.admin.v1.GatewayService.UpdateGateway:input_type -> ingate.admin.v1.UpdateGatewayRequest
	8,  // 13: ingate.admin.v1.GatewayService.DeleteGateway:input_type -> ingate.admin.v1.DeleteGatewayRequest
	4,  // 14: ingate.admin.v1.GatewayService.ListGateways:output_type -> ingate.admin.v1.ListGatewaysResponse
	2,  // 15: ingate.admin.v1.GatewayService.GetGateway:output_type -> ingate.admin.v1.Gateway
	2,  // 16: ingate.admin.v1.GatewayService.CreateGateway:output_type -> ingate.admin.v1.Gateway
	2,  // 17: ingate.admin.v1.GatewayService.UpdateGateway:output_type -> ingate.admin.v1.Gateway
	11, // 18: ingate.admin.v1.GatewayService.DeleteGateway:output_type -> google.protobuf.Empty
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_admin_v1_gateway_proto_init() }
func file_admin_v1_gateway_proto_init() {
	if File_admin_v1_gateway_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	file_admin_v1_gateway_proto_msgTypes[2].OneofWrappers = []any{}
	file_admin_v1_gateway_proto_msgTypes[5].OneofWrappers = []any{}
	file_admin_v1_gateway_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_gateway_proto_rawDesc), len(file_admin_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_gateway_proto_goTypes,
		DependencyIndexes: file_admin_v1_gateway_proto_depIdxs,
		EnumInfos:         file_admin_v1_gateway_proto_enumTypes,
		MessageInfos:      file_admin_v1_gateway_proto_msgTypes,
	}.Build()
	File_admin_v1_gateway_proto = out.File
	file_admin_v1_gateway_proto_goTypes = nil
	file_admin_v1_gateway_proto_depIdxs = nil
}
