// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/mock_response_policy.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationMockResponsePolicyServiceCreateMockResponsePolicy = "/ingate.admin.v1.MockResponsePolicyService/CreateMockResponsePolicy"
const OperationMockResponsePolicyServiceDeleteMockResponsePolicy = "/ingate.admin.v1.MockResponsePolicyService/DeleteMockResponsePolicy"
const OperationMockResponsePolicyServiceGetMockResponsePolicy = "/ingate.admin.v1.MockResponsePolicyService/GetMockResponsePolicy"
const OperationMockResponsePolicyServiceListMockResponsePolicies = "/ingate.admin.v1.MockResponsePolicyService/ListMockResponsePolicies"
const OperationMockResponsePolicyServiceUpdateMockResponsePolicy = "/ingate.admin.v1.MockResponsePolicyService/UpdateMockResponsePolicy"

type MockResponsePolicyServiceHTTPServer interface {
	CreateMockResponsePolicy(context.Context, *CreateMockResponsePolicyRequest) (*MockResponsePolicy, error)
	DeleteMockResponsePolicy(context.Context, *DeleteMockResponsePolicyRequest) (*emptypb.Empty, error)
	GetMockResponsePolicy(context.Context, *GetMockResponsePolicyRequest) (*MockResponsePolicy, error)
	ListMockResponsePolicies(context.Context, *ListMockResponsePoliciesRequest) (*ListMockResponsePoliciesResponse, error)
	UpdateMockResponsePolicy(context.Context, *UpdateMockResponsePolicyRequest) (*MockResponsePolicy, error)
}

func RegisterMockResponsePolicyServiceHTTPServer(s *http.Server, srv MockResponsePolicyServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/mock-response-policies", _MockResponsePolicyService_ListMockResponsePolicies0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/mock-response-policies/{id}", _MockResponsePolicyService_GetMockResponsePolicy0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/mock-response-policies", _MockResponsePolicyService_CreateMockResponsePolicy0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/mock-response-policies/{id}", _MockResponsePolicyService_UpdateMockResponsePolicy0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/v1/mock-response-policies/{id}", _MockResponsePolicyService_DeleteMockResponsePolicy0_HTTP_Handler(srv))
}

func _MockResponsePolicyService_ListMockResponsePolicies0_HTTP_Handler(srv MockResponsePolicyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMockResponsePoliciesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMockResponsePolicyServiceListMockResponsePolicies)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMockResponsePolicies(ctx, req.(*ListMockResponsePoliciesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMockResponsePoliciesResponse)
		return ctx.Result(200, reply)
	}
}

func _MockResponsePolicyService_GetMockResponsePolicy0_HTTP_Handler(srv MockResponsePolicyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMockResponsePolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMockResponsePolicyServiceGetMockResponsePolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMockResponsePolicy(ctx, req.(*GetMockResponsePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MockResponsePolicy)
		return ctx.Result(200, reply)
	}
}

func _MockResponsePolicyService_CreateMockResponsePolicy0_HTTP_Handler(srv MockResponsePolicyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMockResponsePolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMockResponsePolicyServiceCreateMockResponsePolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMockResponsePolicy(ctx, req.(*CreateMockResponsePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MockResponsePolicy)
		return ctx.Result(200, reply)
	}
}

func _MockResponsePolicyService_UpdateMockResponsePolicy0_HTTP_Handler(srv MockResponsePolicyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMockResponsePolicyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMockResponsePolicyServiceUpdateMockResponsePolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMockResponsePolicy(ctx, req.(*UpdateMockResponsePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MockResponsePolicy)
		return ctx.Result(200, reply)
	}
}

func _MockResponsePolicyService_DeleteMockResponsePolicy0_HTTP_Handler(srv MockResponsePolicyServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMockResponsePolicyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMockResponsePolicyServiceDeleteMockResponsePolicy)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMockResponsePolicy(ctx, req.(*DeleteMockResponsePolicyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type MockResponsePolicyServiceHTTPClient interface {
	CreateMockResponsePolicy(ctx context.Context, req *CreateMockResponsePolicyRequest, opts ...http.CallOption) (rsp *MockResponsePolicy, err error)
	DeleteMockResponsePolicy(ctx context.Context, req *DeleteMockResponsePolicyRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetMockResponsePolicy(ctx context.Context, req *GetMockResponsePolicyRequest, opts ...http.CallOption) (rsp *MockResponsePolicy, err error)
	ListMockResponsePolicies(ctx context.Context, req *ListMockResponsePoliciesRequest, opts ...http.CallOption) (rsp *ListMockResponsePoliciesResponse, err error)
	UpdateMockResponsePolicy(ctx context.Context, req *UpdateMockResponsePolicyRequest, opts ...http.CallOption) (rsp *MockResponsePolicy, err error)
}

type MockResponsePolicyServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMockResponsePolicyServiceHTTPClient(client *http.Client) MockResponsePolicyServiceHTTPClient {
	return &MockResponsePolicyServiceHTTPClientImpl{client}
}

func (c *MockResponsePolicyServiceHTTPClientImpl) CreateMockResponsePolicy(ctx context.Context, in *CreateMockResponsePolicyRequest, opts ...http.CallOption) (*MockResponsePolicy, error) {
	var out MockResponsePolicy
	pattern := "/api/v1/mock-response-policies"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMockResponsePolicyServiceCreateMockResponsePolicy),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MockResponsePolicyServiceHTTPClientImpl) DeleteMockResponsePolicy(ctx context.Context, in *DeleteMockResponsePolicyRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/mock-response-policies/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMockResponsePolicyServiceDeleteMockResponsePolicy),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MockResponsePolicyServiceHTTPClientImpl) GetMockResponsePolicy(ctx context.Context, in *GetMockResponsePolicyRequest, opts ...http.CallOption) (*MockResponsePolicy, error) {
	var out MockResponsePolicy
	pattern := "/api/v1/mock-response-policies/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMockResponsePolicyServiceGetMockResponsePolicy),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MockResponsePolicyServiceHTTPClientImpl) ListMockResponsePolicies(ctx context.Context, in *ListMockResponsePoliciesRequest, opts ...http.CallOption) (*ListMockResponsePoliciesResponse, error) {
	var out ListMockResponsePoliciesResponse
	pattern := "/api/v1/mock-response-policies"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationMockResponsePolicyServiceListMockResponsePolicies),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MockResponsePolicyServiceHTTPClientImpl) UpdateMockResponsePolicy(ctx context.Context, in *UpdateMockResponsePolicyRequest, opts ...http.CallOption) (*MockResponsePolicy, error) {
	var out MockResponsePolicy
	pattern := "/api/v1/mock-response-policies/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationMockResponsePolicyServiceUpdateMockResponsePolicy),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
