// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: admin/v1/request_record.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestRecordService_ListRequestRecords_FullMethodName = "/ingate.admin.v1.RequestRecordService/ListRequestRecords"
	RequestRecordService_GetRequestRecord_FullMethodName   = "/ingate.admin.v1.RequestRecordService/GetRequestRecord"
)

// RequestRecordServiceClient is the client API for RequestRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RequestRecordService 提供网关请求明细查询接口
type RequestRecordServiceClient interface {
	// ListRequestRecords 按时间倒序查询请求记录
	ListRequestRecords(ctx context.Context, in *ListRequestRecordsRequest, opts ...grpc.CallOption) (*ListRequestRecordsResponse, error)
	// GetRequestRecord 查询一次请求的完整元数据
	GetRequestRecord(ctx context.Context, in *GetRequestRecordRequest, opts ...grpc.CallOption) (*RequestRecord, error)
}

type requestRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestRecordServiceClient(cc grpc.ClientConnInterface) RequestRecordServiceClient {
	return &requestRecordServiceClient{cc}
}

func (c *requestRecordServiceClient) ListRequestRecords(ctx context.Context, in *ListRequestRecordsRequest, opts ...grpc.CallOption) (*ListRequestRecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRequestRecordsResponse)
	err := c.cc.Invoke(ctx, RequestRecordService_ListRequestRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestRecordServiceClient) GetRequestRecord(ctx context.Context, in *GetRequestRecordRequest, opts ...grpc.CallOption) (*RequestRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestRecord)
	err := c.cc.Invoke(ctx, RequestRecordService_GetRequestRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestRecordServiceServer is the server API for RequestRecordService service.
// All implementations should embed UnimplementedRequestRecordServiceServer
// for forward compatibility.
//
// RequestRecordService 提供网关请求明细查询接口
type RequestRecordServiceServer interface {
	// ListRequestRecords 按时间倒序查询请求记录
	ListRequestRecords(context.Context, *ListRequestRecordsRequest) (*ListRequestRecordsResponse, error)
	// GetRequestRecord 查询一次请求的完整元数据
	GetRequestRecord(context.Context, *GetRequestRecordRequest) (*RequestRecord, error)
}

// UnimplementedRequestRecordServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestRecordServiceServer struct{}

func (UnimplementedRequestRecordServiceServer) ListRequestRecords(context.Context, *ListRequestRecordsRequest) (*ListRequestRecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRequestRecords not implemented")
}
func (UnimplementedRequestRecordServiceServer) GetRequestRecord(context.Context, *GetRequestRecordRequest) (*RequestRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRequestRecord not implemented")
}
func (UnimplementedRequestRecordServiceServer) testEmbeddedByValue() {}

// UnsafeRequestRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestRecordServiceServer will
// result in compilation errors.
type UnsafeRequestRecordServiceServer interface {
	mustEmbedUnimplementedRequestRecordServiceServer()
}

func RegisterRequestRecordServiceServer(s grpc.ServiceRegistrar, srv RequestRecordServiceServer) {
	// If the following call panics, it indicates UnimplementedRequestRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestRecordService_ServiceDesc, srv)
}

func _RequestRecordService_ListRequestRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRecordServiceServer).ListRequestRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRecordService_ListRequestRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRecordServiceServer).ListRequestRecords(ctx, req.(*ListRequestRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestRecordService_GetRequestRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestRecordServiceServer).GetRequestRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestRecordService_GetRequestRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestRecordServiceServer).GetRequestRecord(ctx, req.(*GetRequestRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestRecordService_ServiceDesc is the grpc.ServiceDesc for RequestRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ingate.admin.v1.RequestRecordService",
	HandlerType: (*RequestRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRequestRecords",
			Handler:    _RequestRecordService_ListRequestRecords_Handler,
		},
		{
			MethodName: "GetRequestRecord",
			Handler:    _RequestRecordService_GetRequestRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/request_record.proto",
}
