// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/route.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationRouteServiceCreateRoute = "/ingate.admin.v1.RouteService/CreateRoute"
const OperationRouteServiceDeleteRoute = "/ingate.admin.v1.RouteService/DeleteRoute"
const OperationRouteServiceGetRoute = "/ingate.admin.v1.RouteService/GetRoute"
const OperationRouteServiceListRoutes = "/ingate.admin.v1.RouteService/ListRoutes"
const OperationRouteServiceUpdateRoute = "/ingate.admin.v1.RouteService/UpdateRoute"

type RouteServiceHTTPServer interface {
	// CreateRoute CreateRoute 创建 Route。
	CreateRoute(context.Context, *CreateRouteRequest) (*Route, error)
	// DeleteRoute DeleteRoute 使用资源版本删除 Route。
	DeleteRoute(context.Context, *DeleteRouteRequest) (*emptypb.Empty, error)
	// GetRoute GetRoute 查询指定 Route。
	GetRoute(context.Context, *GetRouteRequest) (*Route, error)
	// ListRoutes ListRoutes 分页查询 Route。
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	// UpdateRoute UpdateRoute 使用资源版本完整替换 Route 配置。
	UpdateRoute(context.Context, *UpdateRouteRequest) (*Route, error)
}

func RegisterRouteServiceHTTPServer(s *http.Server, srv RouteServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/routes", _RouteService_ListRoutes0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/routes/{id}", _RouteService_GetRoute0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/routes", _RouteService_CreateRoute0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/routes/{id}", _RouteService_UpdateRoute0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/v1/routes/{id}", _RouteService_DeleteRoute0_HTTP_Handler(srv))
}

func _RouteService_ListRoutes0_HTTP_Handler(srv RouteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRoutesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteServiceListRoutes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoutes(ctx, req.(*ListRoutesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRoutesResponse)
		return ctx.Result(200, reply)
	}
}

func _RouteService_GetRoute0_HTTP_Handler(srv RouteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRouteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteServiceGetRoute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRoute(ctx, req.(*GetRouteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Route)
		return ctx.Result(200, reply)
	}
}

func _RouteService_CreateRoute0_HTTP_Handler(srv RouteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRouteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteServiceCreateRoute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRoute(ctx, req.(*CreateRouteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Route)
		return ctx.Result(200, reply)
	}
}

func _RouteService_UpdateRoute0_HTTP_Handler(srv RouteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRouteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteServiceUpdateRoute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRoute(ctx, req.(*UpdateRouteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Route)
		return ctx.Result(200, reply)
	}
}

func _RouteService_DeleteRoute0_HTTP_Handler(srv RouteServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRouteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRouteServiceDeleteRoute)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRoute(ctx, req.(*DeleteRouteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type RouteServiceHTTPClient interface {
	// CreateRoute CreateRoute 创建 Route。
	CreateRoute(ctx context.Context, req *CreateRouteRequest, opts ...http.CallOption) (rsp *Route, err error)
	// DeleteRoute DeleteRoute 使用资源版本删除 Route。
	DeleteRoute(ctx context.Context, req *DeleteRouteRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetRoute GetRoute 查询指定 Route。
	GetRoute(ctx context.Context, req *GetRouteRequest, opts ...http.CallOption) (rsp *Route, err error)
	// ListRoutes ListRoutes 分页查询 Route。
	ListRoutes(ctx context.Context, req *ListRoutesRequest, opts ...http.CallOption) (rsp *ListRoutesResponse, err error)
	// UpdateRoute UpdateRoute 使用资源版本完整替换 Route 配置。
	UpdateRoute(ctx context.Context, req *UpdateRouteRequest, opts ...http.CallOption) (rsp *Route, err error)
}

type RouteServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRouteServiceHTTPClient(client *http.Client) RouteServiceHTTPClient {
	return &RouteServiceHTTPClientImpl{client}
}

// CreateRoute CreateRoute 创建 Route。
func (c *RouteServiceHTTPClientImpl) CreateRoute(ctx context.Context, in *CreateRouteRequest, opts ...http.CallOption) (*Route, error) {
	var out Route
	pattern := "/api/v1/routes"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRouteServiceCreateRoute),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteRoute DeleteRoute 使用资源版本删除 Route。
func (c *RouteServiceHTTPClientImpl) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/routes/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRouteServiceDeleteRoute),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRoute GetRoute 查询指定 Route。
func (c *RouteServiceHTTPClientImpl) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...http.CallOption) (*Route, error) {
	var out Route
	pattern := "/api/v1/routes/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRouteServiceGetRoute),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRoutes ListRoutes 分页查询 Route。
func (c *RouteServiceHTTPClientImpl) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...http.CallOption) (*ListRoutesResponse, error) {
	var out ListRoutesResponse
	pattern := "/api/v1/routes"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationRouteServiceListRoutes),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateRoute UpdateRoute 使用资源版本完整替换 Route 配置。
func (c *RouteServiceHTTPClientImpl) UpdateRoute(ctx context.Context, in *UpdateRouteRequest, opts ...http.CallOption) (*Route, error) {
	var out Route
	pattern := "/api/v1/routes/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationRouteServiceUpdateRoute),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
