// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/service.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationServiceManagementServiceCreateService = "/ingate.admin.v1.ServiceManagementService/CreateService"
const OperationServiceManagementServiceDeleteService = "/ingate.admin.v1.ServiceManagementService/DeleteService"
const OperationServiceManagementServiceGetService = "/ingate.admin.v1.ServiceManagementService/GetService"
const OperationServiceManagementServiceListServices = "/ingate.admin.v1.ServiceManagementService/ListServices"
const OperationServiceManagementServiceUpdateService = "/ingate.admin.v1.ServiceManagementService/UpdateService"

type ServiceManagementServiceHTTPServer interface {
	// CreateService CreateService 创建 Service，资源 ID 由服务端生成。
	CreateService(context.Context, *CreateServiceRequest) (*Service, error)
	// DeleteService DeleteService 使用资源版本删除 Service。
	DeleteService(context.Context, *DeleteServiceRequest) (*emptypb.Empty, error)
	// GetService GetService 查询指定 Service。
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	// ListServices ListServices 分页查询 Service。
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// UpdateService UpdateService 使用资源版本完整替换 Service 配置。
	UpdateService(context.Context, *UpdateServiceRequest) (*Service, error)
}

func RegisterServiceManagementServiceHTTPServer(s *http.Server, srv ServiceManagementServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/services", _ServiceManagementService_ListServices0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/services/{id}", _ServiceManagementService_GetService0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/services", _ServiceManagementService_CreateService0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/services/{id}", _ServiceManagementService_UpdateService0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/v1/services/{id}", _ServiceManagementService_DeleteService0_HTTP_Handler(srv))
}

func _ServiceManagementService_ListServices0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListServicesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceListServices)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListServices(ctx, req.(*ListServicesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListServicesResponse)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_GetService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetServiceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceGetService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetService(ctx, req.(*GetServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Service)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_CreateService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceCreateService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateService(ctx, req.(*CreateServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Service)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_UpdateService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceUpdateService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateService(ctx, req.(*UpdateServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Service)
		return ctx.Result(200, reply)
	}
}

func _ServiceManagementService_DeleteService0_HTTP_Handler(srv ServiceManagementServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteServiceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServiceManagementServiceDeleteService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteService(ctx, req.(*DeleteServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ServiceManagementServiceHTTPClient interface {
	// CreateService CreateService 创建 Service，资源 ID 由服务端生成。
	CreateService(ctx context.Context, req *CreateServiceRequest, opts ...http.CallOption) (rsp *Service, err error)
	// DeleteService DeleteService 使用资源版本删除 Service。
	DeleteService(ctx context.Context, req *DeleteServiceRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetService GetService 查询指定 Service。
	GetService(ctx context.Context, req *GetServiceRequest, opts ...http.CallOption) (rsp *Service, err error)
	// ListServices ListServices 分页查询 Service。
	ListServices(ctx context.Context, req *ListServicesRequest, opts ...http.CallOption) (rsp *ListServicesResponse, err error)
	// UpdateService UpdateService 使用资源版本完整替换 Service 配置。
	UpdateService(ctx context.Context, req *UpdateServiceRequest, opts ...http.CallOption) (rsp *Service, err error)
}

type ServiceManagementServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewServiceManagementServiceHTTPClient(client *http.Client) ServiceManagementServiceHTTPClient {
	return &ServiceManagementServiceHTTPClientImpl{client}
}

// CreateService CreateService 创建 Service，资源 ID 由服务端生成。
func (c *ServiceManagementServiceHTTPClientImpl) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...http.CallOption) (*Service, error) {
	var out Service
	pattern := "/api/v1/services"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationServiceManagementServiceCreateService),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteService DeleteService 使用资源版本删除 Service。
func (c *ServiceManagementServiceHTTPClientImpl) DeleteService(ctx context.Context, in *DeleteServiceRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/services/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationServiceManagementServiceDeleteService),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetService GetService 查询指定 Service。
func (c *ServiceManagementServiceHTTPClientImpl) GetService(ctx context.Context, in *GetServiceRequest, opts ...http.CallOption) (*Service, error) {
	var out Service
	pattern := "/api/v1/services/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationServiceManagementServiceGetService),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListServices ListServices 分页查询 Service。
func (c *ServiceManagementServiceHTTPClientImpl) ListServices(ctx context.Context, in *ListServicesRequest, opts ...http.CallOption) (*ListServicesResponse, error) {
	var out ListServicesResponse
	pattern := "/api/v1/services"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationServiceManagementServiceListServices),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateService UpdateService 使用资源版本完整替换 Service 配置。
func (c *ServiceManagementServiceHTTPClientImpl) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...http.CallOption) (*Service, error) {
	var out Service
	pattern := "/api/v1/services/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationServiceManagementServiceUpdateService),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
