// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/token_quota_policy.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenQuotaSubject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	HeaderName    string                 `protobuf:"bytes,2,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenQuotaSubject) Reset() {
	*x = TokenQuotaSubject{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenQuotaSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenQuotaSubject) ProtoMessage() {}

func (x *TokenQuotaSubject) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenQuotaSubject.ProtoReflect.Descriptor instead.
func (*TokenQuotaSubject) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{0}
}

func (x *TokenQuotaSubject) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TokenQuotaSubject) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

type TokenQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        int64                  `protobuf:"varint,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	WindowSeconds int64                  `protobuf:"varint,2,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenQuota) Reset() {
	*x = TokenQuota{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenQuota) ProtoMessage() {}

func (x *TokenQuota) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenQuota.ProtoReflect.Descriptor instead.
func (*TokenQuota) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{1}
}

func (x *TokenQuota) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *TokenQuota) GetWindowSeconds() int64 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type TokenQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenQuotaResponse) Reset() {
	*x = TokenQuotaResponse{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenQuotaResponse) ProtoMessage() {}

func (x *TokenQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenQuotaResponse.ProtoReflect.Descriptor instead.
func (*TokenQuotaResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{2}
}

func (x *TokenQuotaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TokenQuotaPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        *ResourceStatus        `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTarget        `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	Subject       *TokenQuotaSubject     `protobuf:"bytes,8,opt,name=subject,proto3" json:"subject,omitempty"`
	Quota         *TokenQuota            `protobuf:"bytes,9,opt,name=quota,proto3" json:"quota,omitempty"`
	FailurePolicy string                 `protobuf:"bytes,10,opt,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty"`
	Response      *TokenQuotaResponse    `protobuf:"bytes,11,opt,name=response,proto3" json:"response,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenQuotaPolicy) Reset() {
	*x = TokenQuotaPolicy{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenQuotaPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenQuotaPolicy) ProtoMessage() {}

func (x *TokenQuotaPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenQuotaPolicy.ProtoReflect.Descriptor instead.
func (*TokenQuotaPolicy) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{3}
}

func (x *TokenQuotaPolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TokenQuotaPolicy) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TokenQuotaPolicy) GetStatus() *ResourceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TokenQuotaPolicy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenQuotaPolicy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TokenQuotaPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TokenQuotaPolicy) GetTargets() []*PolicyTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *TokenQuotaPolicy) GetSubject() *TokenQuotaSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *TokenQuotaPolicy) GetQuota() *TokenQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *TokenQuotaPolicy) GetFailurePolicy() string {
	if x != nil {
		return x.FailurePolicy
	}
	return ""
}

func (x *TokenQuotaPolicy) GetResponse() *TokenQuotaResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *TokenQuotaPolicy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTokenQuotaPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTargetRef     `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Subject       *TokenQuotaSubject     `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Quota         *TokenQuota            `protobuf:"bytes,6,opt,name=quota,proto3" json:"quota,omitempty"`
	FailurePolicy string                 `protobuf:"bytes,7,opt,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty"`
	Response      *TokenQuotaResponse    `protobuf:"bytes,8,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenQuotaPolicyRequest) Reset() {
	*x = CreateTokenQuotaPolicyRequest{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenQuotaPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenQuotaPolicyRequest) ProtoMessage() {}

func (x *CreateTokenQuotaPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenQuotaPolicyRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenQuotaPolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTokenQuotaPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTokenQuotaPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTokenQuotaPolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreateTokenQuotaPolicyRequest) GetTargets() []*PolicyTargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CreateTokenQuotaPolicyRequest) GetSubject() *TokenQuotaSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CreateTokenQuotaPolicyRequest) GetQuota() *TokenQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *CreateTokenQuotaPolicyRequest) GetFailurePolicy() string {
	if x != nil {
		return x.FailurePolicy
	}
	return ""
}

func (x *CreateTokenQuotaPolicyRequest) GetResponse() *TokenQuotaResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type UpdateTokenQuotaPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Targets       []*PolicyTargetRef     `protobuf:"bytes,6,rep,name=targets,proto3" json:"targets,omitempty"`
	Subject       *TokenQuotaSubject     `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`
	Quota         *TokenQuota            `protobuf:"bytes,8,opt,name=quota,proto3" json:"quota,omitempty"`
	FailurePolicy string                 `protobuf:"bytes,9,opt,name=failure_policy,json=failurePolicy,proto3" json:"failure_policy,omitempty"`
	Response      *TokenQuotaResponse    `protobuf:"bytes,10,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenQuotaPolicyRequest) Reset() {
	*x = UpdateTokenQuotaPolicyRequest{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenQuotaPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenQuotaPolicyRequest) ProtoMessage() {}

func (x *UpdateTokenQuotaPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenQuotaPolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdateTokenQuotaPolicyRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTokenQuotaPolicyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTokenQuotaPolicyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateTokenQuotaPolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTokenQuotaPolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTokenQuotaPolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateTokenQuotaPolicyRequest) GetTargets() []*PolicyTargetRef {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *UpdateTokenQuotaPolicyRequest) GetSubject() *TokenQuotaSubject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *UpdateTokenQuotaPolicyRequest) GetQuota() *TokenQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *UpdateTokenQuotaPolicyRequest) GetFailurePolicy() string {
	if x != nil {
		return x.FailurePolicy
	}
	return ""
}

func (x *UpdateTokenQuotaPolicyRequest) GetResponse() *TokenQuotaResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListTokenQuotaPoliciesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*TokenQuotaPolicy    `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	Page          *PageInfo              `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokenQuotaPoliciesReply) Reset() {
	*x = ListTokenQuotaPoliciesReply{}
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokenQuotaPoliciesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokenQuotaPoliciesReply) ProtoMessage() {}

func (x *ListTokenQuotaPoliciesReply) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_token_quota_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokenQuotaPoliciesReply.ProtoReflect.Descriptor instead.
func (*ListTokenQuotaPoliciesReply) Descriptor() ([]byte, []int) {
	return file_admin_v1_token_quota_policy_proto_rawDescGZIP(), []int{6}
}

func (x *ListTokenQuotaPoliciesReply) GetPolicies() []*TokenQuotaPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *ListTokenQuotaPoliciesReply) GetPage() *PageInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_admin_v1_token_quota_policy_proto protoreflect.FileDescriptor

const file_admin_v1_token_quota_policy_proto_rawDesc = "" +
	"\n" +
	"!admin/v1/token_quota_policy.proto\x12\x0fingate.admin.v1\x1a\x15admin/v1/common.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\x11TokenQuotaSubject\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vheader_name\x18\x02 \x01(\tR\n" +
	"headerName\"K\n" +
	"\n" +
	"TokenQuota\x12\x16\n" +
	"\x06tokens\x18\x01 \x01(\x03R\x06tokens\x12%\n" +
	"\x0ewindow_seconds\x18\x02 \x01(\x03R\rwindowSeconds\".\n" +
	"\x12TokenQuotaResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x92\x04\n" +
	"\x10TokenQuotaPolicy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x127\n" +
	"\x06status\x18\x03 \x01(\v2\x1f.ingate.admin.v1.ResourceStatusR\x06status\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x127\n" +
	"\atargets\x18\a \x03(\v2\x1d.ingate.admin.v1.PolicyTargetR\atargets\x12<\n" +
	"\asubject\x18\b \x01(\v2\".ingate.admin.v1.TokenQuotaSubjectR\asubject\x121\n" +
	"\x05quota\x18\t \x01(\v2\x1b.ingate.admin.v1.TokenQuotaR\x05quota\x12%\n" +
	"\x0efailure_policy\x18\n" +
	" \x01(\tR\rfailurePolicy\x12?\n" +
	"\bresponse\x18\v \x01(\v2#.ingate.admin.v1.TokenQuotaResponseR\bresponse\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa6\x03\n" +
	"\x1dCreateTokenQuotaPolicyRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12:\n" +
	"\atargets\x18\x04 \x03(\v2 .ingate.admin.v1.PolicyTargetRefR\atargets\x12D\n" +
	"\asubject\x18\x05 \x01(\v2\".ingate.admin.v1.TokenQuotaSubjectB\x06\xbaH\x03\xc8\x01\x01R\asubject\x129\n" +
	"\x05quota\x18\x06 \x01(\v2\x1b.ingate.admin.v1.TokenQuotaB\x06\xbaH\x03\xc8\x01\x01R\x05quota\x12.\n" +
	"\x0efailure_policy\x18\a \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rfailurePolicy\x12?\n" +
	"\bresponse\x18\b \x01(\v2#.ingate.admin.v1.TokenQuotaResponseR\bresponse\"\xe4\x03\n" +
	"\x1dUpdateTokenQuotaPolicyRequest\x12\x19\n" +
	"\x02id\x18\x01 \x01(\tB\t\xbaH\x06r\x042\x02\\SR\x02id\x12!\n" +
	"\aversion\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aversion\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12:\n" +
	"\atargets\x18\x06 \x03(\v2 .ingate.admin.v1.PolicyTargetRefR\atargets\x12D\n" +
	"\asubject\x18\a \x01(\v2\".ingate.admin.v1.TokenQuotaSubjectB\x06\xbaH\x03\xc8\x01\x01R\asubject\x129\n" +
	"\x05quota\x18\b \x01(\v2\x1b.ingate.admin.v1.TokenQuotaB\x06\xbaH\x03\xc8\x01\x01R\x05quota\x12.\n" +
	"\x0efailure_policy\x18\t \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rfailurePolicy\x12?\n" +
	"\bresponse\x18\n" +
	" \x01(\v2#.ingate.admin.v1.TokenQuotaResponseR\bresponse\"\x8b\x01\n" +
	"\x1bListTokenQuotaPoliciesReply\x12=\n" +
	"\bpolicies\x18\x01 \x03(\v2!.ingate.admin.v1.TokenQuotaPolicyR\bpolicies\x12-\n" +
	"\x04page\x18\x02 \x01(\v2\x19.ingate.admin.v1.PageInfoR\x04page2\xfc\x06\n" +
	"\x17TokenQuotaPolicyService\x12\x8a\x01\n" +
	"\x16ListTokenQuotaPolicies\x12\x1c.ingate.admin.v1.ListRequest\x1a,.ingate.admin.v1.ListTokenQuotaPoliciesReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/token-quota-policies\x12\x85\x01\n" +
	"\x13GetTokenQuotaPolicy\x12 .ingate.admin.v1.ResourceRequest\x1a!.ingate.admin.v1.TokenQuotaPolicy\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/token-quota-policies/{id}\x12\x91\x01\n" +
	"\x16CreateTokenQuotaPolicy\x12..ingate.admin.v1.CreateTokenQuotaPolicyRequest\x1a\x1e.ingate.admin.v1.MutationReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/token-quota-policies\x12\x96\x01\n" +
	"\x16UpdateTokenQuotaPolicy\x12..ingate.admin.v1.UpdateTokenQuotaPolicyRequest\x1a\x1e.ingate.admin.v1.MutationReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/v1/token-quota-policies/{id}\x12\x96\x01\n" +
	"\x1aSetTokenQuotaPolicyEnabled\x12\".ingate.admin.v1.SetEnabledRequest\x1a\x1e.ingate.admin.v1.MutationReply\"4\x82\xd3\xe4\x93\x02.:\x01*2)/api/v1/token-quota-policies/{id}/enabled\x12\x85\x01\n" +
	"\x16DeleteTokenQuotaPolicy\x12 .ingate.admin.v1.ResourceRequest\x1a\x1e.ingate.admin.v1.MutationReply\")\x82\xd3\xe4\x93\x02#*!/api/v1/token-quota-policies/{id}B*Z(github.com/lgc202/ingate/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_token_quota_policy_proto_rawDescOnce sync.Once
	file_admin_v1_token_quota_policy_proto_rawDescData []byte
)

func file_admin_v1_token_quota_policy_proto_rawDescGZIP() []byte {
	file_admin_v1_token_quota_policy_proto_rawDescOnce.Do(func() {
		file_admin_v1_token_quota_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_token_quota_policy_proto_rawDesc), len(file_admin_v1_token_quota_policy_proto_rawDesc)))
	})
	return file_admin_v1_token_quota_policy_proto_rawDescData
}

var file_admin_v1_token_quota_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_admin_v1_token_quota_policy_proto_goTypes = []any{
	(*TokenQuotaSubject)(nil),             // 0: ingate.admin.v1.TokenQuotaSubject
	(*TokenQuota)(nil),                    // 1: ingate.admin.v1.TokenQuota
	(*TokenQuotaResponse)(nil),            // 2: ingate.admin.v1.TokenQuotaResponse
	(*TokenQuotaPolicy)(nil),              // 3: ingate.admin.v1.TokenQuotaPolicy
	(*CreateTokenQuotaPolicyRequest)(nil), // 4: ingate.admin.v1.CreateTokenQuotaPolicyRequest
	(*UpdateTokenQuotaPolicyRequest)(nil), // 5: ingate.admin.v1.UpdateTokenQuotaPolicyRequest
	(*ListTokenQuotaPoliciesReply)(nil),   // 6: ingate.admin.v1.ListTokenQuotaPoliciesReply
	(*ResourceStatus)(nil),                // 7: ingate.admin.v1.ResourceStatus
	(*PolicyTarget)(nil),                  // 8: ingate.admin.v1.PolicyTarget
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
	(*PolicyTargetRef)(nil),               // 10: ingate.admin.v1.PolicyTargetRef
	(*PageInfo)(nil),                      // 11: ingate.admin.v1.PageInfo
	(*ListRequest)(nil),                   // 12: ingate.admin.v1.ListRequest
	(*ResourceRequest)(nil),               // 13: ingate.admin.v1.ResourceRequest
	(*SetEnabledRequest)(nil),             // 14: ingate.admin.v1.SetEnabledRequest
	(*MutationReply)(nil),                 // 15: ingate.admin.v1.MutationReply
}
var file_admin_v1_token_quota_policy_proto_depIdxs = []int32{
	7,  // 0: ingate.admin.v1.TokenQuotaPolicy.status:type_name -> ingate.admin.v1.ResourceStatus
	8,  // 1: ingate.admin.v1.TokenQuotaPolicy.targets:type_name -> ingate.admin.v1.PolicyTarget
	0,  // 2: ingate.admin.v1.TokenQuotaPolicy.subject:type_name -> ingate.admin.v1.TokenQuotaSubject
	1,  // 3: ingate.admin.v1.TokenQuotaPolicy.quota:type_name -> ingate.admin.v1.TokenQuota
	2,  // 4: ingate.admin.v1.TokenQuotaPolicy.response:type_name -> ingate.admin.v1.TokenQuotaResponse
	9,  // 5: ingate.admin.v1.TokenQuotaPolicy.created_at:type_name -> google.protobuf.Timestamp
	10, // 6: ingate.admin.v1.CreateTokenQuotaPolicyRequest.targets:type_name -> ingate.admin.v1.PolicyTargetRef
	0,  // 7: ingate.admin.v1.CreateTokenQuotaPolicyRequest.subject:type_name -> ingate.admin.v1.TokenQuotaSubject
	1,  // 8: ingate.admin.v1.CreateTokenQuotaPolicyRequest.quota:type_name -> ingate.admin.v1.TokenQuota
	2,  // 9: ingate.admin.v1.CreateTokenQuotaPolicyRequest.response:type_name -> ingate.admin.v1.TokenQuotaResponse
	10, // 10: ingate.admin.v1.UpdateTokenQuotaPolicyRequest.targets:type_name -> ingate.admin.v1.PolicyTargetRef
	0,  // 11: ingate.admin.v1.UpdateTokenQuotaPolicyRequest.subject:type_name -> ingate.admin.v1.TokenQuotaSubject
	1,  // 12: ingate.admin.v1.UpdateTokenQuotaPolicyRequest.quota:type_name -> ingate.admin.v1.TokenQuota
	2,  // 13: ingate.admin.v1.UpdateTokenQuotaPolicyRequest.response:type_name -> ingate.admin.v1.TokenQuotaResponse
	3,  // 14: ingate.admin.v1.ListTokenQuotaPoliciesReply.policies:type_name -> ingate.admin.v1.TokenQuotaPolicy
	11, // 15: ingate.admin.v1.ListTokenQuotaPoliciesReply.page:type_name -> ingate.admin.v1.PageInfo
	12, // 16: ingate.admin.v1.TokenQuotaPolicyService.ListTokenQuotaPolicies:input_type -> ingate.admin.v1.ListRequest
	13, // 17: ingate.admin.v1.TokenQuotaPolicyService.GetTokenQuotaPolicy:input_type -> ingate.admin.v1.ResourceRequest
	4,  // 18: ingate.admin.v1.TokenQuotaPolicyService.CreateTokenQuotaPolicy:input_type -> ingate.admin.v1.CreateTokenQuotaPolicyRequest
	5,  // 19: ingate.admin.v1.TokenQuotaPolicyService.UpdateTokenQuotaPolicy:input_type -> ingate.admin.v1.UpdateTokenQuotaPolicyRequest
	14, // 20: ingate.admin.v1.TokenQuotaPolicyService.SetTokenQuotaPolicyEnabled:input_type -> ingate.admin.v1.SetEnabledRequest
	13, // 21: ingate.admin.v1.TokenQuotaPolicyService.DeleteTokenQuotaPolicy:input_type -> ingate.admin.v1.ResourceRequest
	6,  // 22: ingate.admin.v1.TokenQuotaPolicyService.ListTokenQuotaPolicies:output_type -> ingate.admin.v1.ListTokenQuotaPoliciesReply
	3,  // 23: ingate.admin.v1.TokenQuotaPolicyService.GetTokenQuotaPolicy:output_type -> ingate.admin.v1.TokenQuotaPolicy
	15, // 24: ingate.admin.v1.TokenQuotaPolicyService.CreateTokenQuotaPolicy:output_type -> ingate.admin.v1.MutationReply
	15, // 25: ingate.admin.v1.TokenQuotaPolicyService.UpdateTokenQuotaPolicy:output_type -> ingate.admin.v1.MutationReply
	15, // 26: ingate.admin.v1.TokenQuotaPolicyService.SetTokenQuotaPolicyEnabled:output_type -> ingate.admin.v1.MutationReply
	15, // 27: ingate.admin.v1.TokenQuotaPolicyService.DeleteTokenQuotaPolicy:output_type -> ingate.admin.v1.MutationReply
	22, // [22:28] is the sub-list for method output_type
	16, // [16:22] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_admin_v1_token_quota_policy_proto_init() }
func file_admin_v1_token_quota_policy_proto_init() {
	if File_admin_v1_token_quota_policy_proto != nil {
		return
	}
	file_admin_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_token_quota_policy_proto_rawDesc), len(file_admin_v1_token_quota_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_token_quota_policy_proto_goTypes,
		DependencyIndexes: file_admin_v1_token_quota_policy_proto_depIdxs,
		MessageInfos:      file_admin_v1_token_quota_policy_proto_msgTypes,
	}.Build()
	File_admin_v1_token_quota_policy_proto = out.File
	file_admin_v1_token_quota_policy_proto_goTypes = nil
	file_admin_v1_token_quota_policy_proto_depIdxs = nil
}
