// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: admin/v1/traffic_analysis.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrafficBreakdownDimension 是流量排名支持的资源维度
type TrafficBreakdownDimension int32

const (
	// TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED 表示使用默认的路由维度
	TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED TrafficBreakdownDimension = 0
	// TRAFFIC_BREAKDOWN_DIMENSION_GATEWAY 按网关排名
	TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_GATEWAY TrafficBreakdownDimension = 1
	// TRAFFIC_BREAKDOWN_DIMENSION_ROUTE 按路由排名
	TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_ROUTE TrafficBreakdownDimension = 2
	// TRAFFIC_BREAKDOWN_DIMENSION_SERVICE 按目标服务排名
	TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_SERVICE TrafficBreakdownDimension = 3
)

// Enum value maps for TrafficBreakdownDimension.
var (
	TrafficBreakdownDimension_name = map[int32]string{
		0: "TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED",
		1: "TRAFFIC_BREAKDOWN_DIMENSION_GATEWAY",
		2: "TRAFFIC_BREAKDOWN_DIMENSION_ROUTE",
		3: "TRAFFIC_BREAKDOWN_DIMENSION_SERVICE",
	}
	TrafficBreakdownDimension_value = map[string]int32{
		"TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED": 0,
		"TRAFFIC_BREAKDOWN_DIMENSION_GATEWAY":     1,
		"TRAFFIC_BREAKDOWN_DIMENSION_ROUTE":       2,
		"TRAFFIC_BREAKDOWN_DIMENSION_SERVICE":     3,
	}
)

func (x TrafficBreakdownDimension) Enum() *TrafficBreakdownDimension {
	p := new(TrafficBreakdownDimension)
	*p = x
	return p
}

func (x TrafficBreakdownDimension) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficBreakdownDimension) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_traffic_analysis_proto_enumTypes[0].Descriptor()
}

func (TrafficBreakdownDimension) Type() protoreflect.EnumType {
	return &file_admin_v1_traffic_analysis_proto_enumTypes[0]
}

func (x TrafficBreakdownDimension) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficBreakdownDimension.Descriptor instead.
func (TrafficBreakdownDimension) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{0}
}

// GetTrafficAnalysisRequest 是流量分析的查询范围
type GetTrafficAnalysisRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_time 是查询范围起点，包含该时刻
	StartTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end_time 是查询范围终点，不包含该时刻
	EndTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// gateway_id 只统计经过指定网关的请求
	GatewayId string `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// route_id 只统计命中指定路由的请求
	RouteId string `protobuf:"bytes,4,opt,name=route_id,json=routeID,proto3" json:"route_id,omitempty"`
	// service_id 只统计最终转发到指定服务的请求
	ServiceId string `protobuf:"bytes,5,opt,name=service_id,json=serviceID,proto3" json:"service_id,omitempty"`
	// breakdown_dimension 指定排名所使用的资源维度
	BreakdownDimension TrafficBreakdownDimension `protobuf:"varint,6,opt,name=breakdown_dimension,json=breakdownDimension,proto3,enum=ingate.admin.v1.TrafficBreakdownDimension" json:"breakdown_dimension,omitempty"`
	// breakdown_limit 是按请求量排序后返回的最大资源数
	BreakdownLimit uint32 `protobuf:"varint,7,opt,name=breakdown_limit,json=breakdownLimit,proto3" json:"breakdown_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTrafficAnalysisRequest) Reset() {
	*x = GetTrafficAnalysisRequest{}
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficAnalysisRequest) ProtoMessage() {}

func (x *GetTrafficAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficAnalysisRequest.ProtoReflect.Descriptor instead.
func (*GetTrafficAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrafficAnalysisRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetTrafficAnalysisRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetTrafficAnalysisRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

func (x *GetTrafficAnalysisRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *GetTrafficAnalysisRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetTrafficAnalysisRequest) GetBreakdownDimension() TrafficBreakdownDimension {
	if x != nil {
		return x.BreakdownDimension
	}
	return TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED
}

func (x *GetTrafficAnalysisRequest) GetBreakdownLimit() uint32 {
	if x != nil {
		return x.BreakdownLimit
	}
	return 0
}

// TrafficMetrics 是一个范围内可直接解释的请求统计
type TrafficMetrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_count 是请求总数
	RequestCount uint64 `protobuf:"varint,1,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	// non_error_count 是获得 1xx 到 3xx 响应的请求数
	NonErrorCount uint64 `protobuf:"varint,2,opt,name=non_error_count,json=nonErrorCount,proto3" json:"non_error_count,omitempty"`
	// client_error_count 是获得 4xx 响应的请求数
	ClientErrorCount uint64 `protobuf:"varint,3,opt,name=client_error_count,json=clientErrorCount,proto3" json:"client_error_count,omitempty"`
	// server_error_count 是获得 5xx 及以上响应的请求数
	ServerErrorCount uint64 `protobuf:"varint,4,opt,name=server_error_count,json=serverErrorCount,proto3" json:"server_error_count,omitempty"`
	// no_response_count 是未获得有效 HTTP 状态码的请求数
	NoResponseCount uint64 `protobuf:"varint,5,opt,name=no_response_count,json=noResponseCount,proto3" json:"no_response_count,omitempty"`
	// average_duration 是平均总耗时
	AverageDuration *durationpb.Duration `protobuf:"bytes,6,opt,name=average_duration,json=averageDuration,proto3" json:"average_duration,omitempty"`
	// p50_duration 是总耗时的 P50 分位值
	P50Duration *durationpb.Duration `protobuf:"bytes,7,opt,name=p50_duration,json=p50Duration,proto3" json:"p50_duration,omitempty"`
	// p95_duration 是总耗时的 P95 分位值
	P95Duration *durationpb.Duration `protobuf:"bytes,8,opt,name=p95_duration,json=p95Duration,proto3" json:"p95_duration,omitempty"`
	// p99_duration 是总耗时的 P99 分位值
	P99Duration   *durationpb.Duration `protobuf:"bytes,9,opt,name=p99_duration,json=p99Duration,proto3" json:"p99_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficMetrics) Reset() {
	*x = TrafficMetrics{}
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficMetrics) ProtoMessage() {}

func (x *TrafficMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficMetrics.ProtoReflect.Descriptor instead.
func (*TrafficMetrics) Descriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *TrafficMetrics) GetRequestCount() uint64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *TrafficMetrics) GetNonErrorCount() uint64 {
	if x != nil {
		return x.NonErrorCount
	}
	return 0
}

func (x *TrafficMetrics) GetClientErrorCount() uint64 {
	if x != nil {
		return x.ClientErrorCount
	}
	return 0
}

func (x *TrafficMetrics) GetServerErrorCount() uint64 {
	if x != nil {
		return x.ServerErrorCount
	}
	return 0
}

func (x *TrafficMetrics) GetNoResponseCount() uint64 {
	if x != nil {
		return x.NoResponseCount
	}
	return 0
}

func (x *TrafficMetrics) GetAverageDuration() *durationpb.Duration {
	if x != nil {
		return x.AverageDuration
	}
	return nil
}

func (x *TrafficMetrics) GetP50Duration() *durationpb.Duration {
	if x != nil {
		return x.P50Duration
	}
	return nil
}

func (x *TrafficMetrics) GetP95Duration() *durationpb.Duration {
	if x != nil {
		return x.P95Duration
	}
	return nil
}

func (x *TrafficMetrics) GetP99Duration() *durationpb.Duration {
	if x != nil {
		return x.P99Duration
	}
	return nil
}

// TrafficAnalysisPoint 是一个时间段内的流量统计
type TrafficAnalysisPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// started_at 是时间段起点
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// metrics 是该时间段内的统计结果
	Metrics       *TrafficMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficAnalysisPoint) Reset() {
	*x = TrafficAnalysisPoint{}
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficAnalysisPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficAnalysisPoint) ProtoMessage() {}

func (x *TrafficAnalysisPoint) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficAnalysisPoint.ProtoReflect.Descriptor instead.
func (*TrafficAnalysisPoint) Descriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficAnalysisPoint) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *TrafficAnalysisPoint) GetMetrics() *TrafficMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// TrafficBreakdownItem 是一个资源的流量统计
type TrafficBreakdownItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resource_id 是排名维度对应的资源 ID
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceID,proto3" json:"resource_id,omitempty"`
	// metrics 是该资源的统计结果
	Metrics       *TrafficMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficBreakdownItem) Reset() {
	*x = TrafficBreakdownItem{}
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficBreakdownItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBreakdownItem) ProtoMessage() {}

func (x *TrafficBreakdownItem) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBreakdownItem.ProtoReflect.Descriptor instead.
func (*TrafficBreakdownItem) Descriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *TrafficBreakdownItem) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TrafficBreakdownItem) GetMetrics() *TrafficMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// GetTrafficAnalysisResponse 是控制台一次展示所需的流量分析结果
type GetTrafficAnalysisResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// summary 是整个查询范围的汇总
	Summary *TrafficMetrics `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// trend 是按时间递增排列的趋势点
	Trend []*TrafficAnalysisPoint `protobuf:"bytes,2,rep,name=trend,proto3" json:"trend,omitempty"`
	// breakdown_dimension 是本次排名使用的资源维度
	BreakdownDimension TrafficBreakdownDimension `protobuf:"varint,3,opt,name=breakdown_dimension,json=breakdownDimension,proto3,enum=ingate.admin.v1.TrafficBreakdownDimension" json:"breakdown_dimension,omitempty"`
	// breakdown 是按请求量倒序排列的资源统计
	Breakdown     []*TrafficBreakdownItem `protobuf:"bytes,4,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrafficAnalysisResponse) Reset() {
	*x = GetTrafficAnalysisResponse{}
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrafficAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrafficAnalysisResponse) ProtoMessage() {}

func (x *GetTrafficAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_traffic_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrafficAnalysisResponse.ProtoReflect.Descriptor instead.
func (*GetTrafficAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_traffic_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *GetTrafficAnalysisResponse) GetSummary() *TrafficMetrics {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetTrafficAnalysisResponse) GetTrend() []*TrafficAnalysisPoint {
	if x != nil {
		return x.Trend
	}
	return nil
}

func (x *GetTrafficAnalysisResponse) GetBreakdownDimension() TrafficBreakdownDimension {
	if x != nil {
		return x.BreakdownDimension
	}
	return TrafficBreakdownDimension_TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED
}

func (x *GetTrafficAnalysisResponse) GetBreakdown() []*TrafficBreakdownItem {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

var File_admin_v1_traffic_analysis_proto protoreflect.FileDescriptor

const file_admin_v1_traffic_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1fadmin/v1/traffic_analysis.proto\x12\x0fingate.admin.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x02\n" +
	"\x19GetTrafficAnalysisRequest\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\tR\tgatewayID\x12\x19\n" +
	"\broute_id\x18\x04 \x01(\tR\arouteID\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceID\x12e\n" +
	"\x13breakdown_dimension\x18\x06 \x01(\x0e2*.ingate.admin.v1.TrafficBreakdownDimensionB\b\xbaH\x05\x82\x01\x02\x10\x01R\x12breakdownDimension\x120\n" +
	"\x0fbreakdown_limit\x18\a \x01(\rB\a\xbaH\x04*\x02\x182R\x0ebreakdownLimit\"\xe5\x03\n" +
	"\x0eTrafficMetrics\x12#\n" +
	"\rrequest_count\x18\x01 \x01(\x04R\frequestCount\x12&\n" +
	"\x0fnon_error_count\x18\x02 \x01(\x04R\rnonErrorCount\x12,\n" +
	"\x12client_error_count\x18\x03 \x01(\x04R\x10clientErrorCount\x12,\n" +
	"\x12server_error_count\x18\x04 \x01(\x04R\x10serverErrorCount\x12*\n" +
	"\x11no_response_count\x18\x05 \x01(\x04R\x0fnoResponseCount\x12D\n" +
	"\x10average_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0faverageDuration\x12<\n" +
	"\fp50_duration\x18\a \x01(\v2\x19.google.protobuf.DurationR\vp50Duration\x12<\n" +
	"\fp95_duration\x18\b \x01(\v2\x19.google.protobuf.DurationR\vp95Duration\x12<\n" +
	"\fp99_duration\x18\t \x01(\v2\x19.google.protobuf.DurationR\vp99Duration\"\x8c\x01\n" +
	"\x14TrafficAnalysisPoint\x129\n" +
	"\n" +
	"started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\ametrics\x18\x02 \x01(\v2\x1f.ingate.admin.v1.TrafficMetricsR\ametrics\"r\n" +
	"\x14TrafficBreakdownItem\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceID\x129\n" +
	"\ametrics\x18\x02 \x01(\v2\x1f.ingate.admin.v1.TrafficMetricsR\ametrics\"\xb6\x02\n" +
	"\x1aGetTrafficAnalysisResponse\x129\n" +
	"\asummary\x18\x01 \x01(\v2\x1f.ingate.admin.v1.TrafficMetricsR\asummary\x12;\n" +
	"\x05trend\x18\x02 \x03(\v2%.ingate.admin.v1.TrafficAnalysisPointR\x05trend\x12[\n" +
	"\x13breakdown_dimension\x18\x03 \x01(\x0e2*.ingate.admin.v1.TrafficBreakdownDimensionR\x12breakdownDimension\x12C\n" +
	"\tbreakdown\x18\x04 \x03(\v2%.ingate.admin.v1.TrafficBreakdownItemR\tbreakdown*\xc1\x01\n" +
	"\x19TrafficBreakdownDimension\x12+\n" +
	"'TRAFFIC_BREAKDOWN_DIMENSION_UNSPECIFIED\x10\x00\x12'\n" +
	"#TRAFFIC_BREAKDOWN_DIMENSION_GATEWAY\x10\x01\x12%\n" +
	"!TRAFFIC_BREAKDOWN_DIMENSION_ROUTE\x10\x02\x12'\n" +
	"#TRAFFIC_BREAKDOWN_DIMENSION_SERVICE\x10\x032\xaa\x01\n" +
	"\x16TrafficAnalysisService\x12\x8f\x01\n" +
	"\x12GetTrafficAnalysis\x12*.ingate.admin.v1.GetTrafficAnalysisRequest\x1a+.ingate.admin.v1.GetTrafficAnalysisResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/traffic-analysisB*Z(github.com/lgc202/ingate/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_traffic_analysis_proto_rawDescOnce sync.Once
	file_admin_v1_traffic_analysis_proto_rawDescData []byte
)

func file_admin_v1_traffic_analysis_proto_rawDescGZIP() []byte {
	file_admin_v1_traffic_analysis_proto_rawDescOnce.Do(func() {
		file_admin_v1_traffic_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_traffic_analysis_proto_rawDesc), len(file_admin_v1_traffic_analysis_proto_rawDesc)))
	})
	return file_admin_v1_traffic_analysis_proto_rawDescData
}

var file_admin_v1_traffic_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_traffic_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_admin_v1_traffic_analysis_proto_goTypes = []any{
	(TrafficBreakdownDimension)(0),     // 0: ingate.admin.v1.TrafficBreakdownDimension
	(*GetTrafficAnalysisRequest)(nil),  // 1: ingate.admin.v1.GetTrafficAnalysisRequest
	(*TrafficMetrics)(nil),             // 2: ingate.admin.v1.TrafficMetrics
	(*TrafficAnalysisPoint)(nil),       // 3: ingate.admin.v1.TrafficAnalysisPoint
	(*TrafficBreakdownItem)(nil),       // 4: ingate.admin.v1.TrafficBreakdownItem
	(*GetTrafficAnalysisResponse)(nil), // 5: ingate.admin.v1.GetTrafficAnalysisResponse
	(*timestamppb.Timestamp)(nil),      // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 7: google.protobuf.Duration
}
var file_admin_v1_traffic_analysis_proto_depIdxs = []int32{
	6,  // 0: ingate.admin.v1.GetTrafficAnalysisRequest.start_time:type_name -> google.protobuf.Timestamp
	6,  // 1: ingate.admin.v1.GetTrafficAnalysisRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: ingate.admin.v1.GetTrafficAnalysisRequest.breakdown_dimension:type_name -> ingate.admin.v1.TrafficBreakdownDimension
	7,  // 3: ingate.admin.v1.TrafficMetrics.average_duration:type_name -> google.protobuf.Duration
	7,  // 4: ingate.admin.v1.TrafficMetrics.p50_duration:type_name -> google.protobuf.Duration
	7,  // 5: ingate.admin.v1.TrafficMetrics.p95_duration:type_name -> google.protobuf.Duration
	7,  // 6: ingate.admin.v1.TrafficMetrics.p99_duration:type_name -> google.protobuf.Duration
	6,  // 7: ingate.admin.v1.TrafficAnalysisPoint.started_at:type_name -> google.protobuf.Timestamp
	2,  // 8: ingate.admin.v1.TrafficAnalysisPoint.metrics:type_name -> ingate.admin.v1.TrafficMetrics
	2,  // 9: ingate.admin.v1.TrafficBreakdownItem.metrics:type_name -> ingate.admin.v1.TrafficMetrics
	2,  // 10: ingate.admin.v1.GetTrafficAnalysisResponse.summary:type_name -> ingate.admin.v1.TrafficMetrics
	3,  // 11: ingate.admin.v1.GetTrafficAnalysisResponse.trend:type_name -> ingate.admin.v1.TrafficAnalysisPoint
	0,  // 12: ingate.admin.v1.GetTrafficAnalysisResponse.breakdown_dimension:type_name -> ingate.admin.v1.TrafficBreakdownDimension
	4,  // 13: ingate.admin.v1.GetTrafficAnalysisResponse.breakdown:type_name -> ingate.admin.v1.TrafficBreakdownItem
	1,  // 14: ingate.admin.v1.TrafficAnalysisService.GetTrafficAnalysis:input_type -> ingate.admin.v1.GetTrafficAnalysisRequest
	5,  // 15: ingate.admin.v1.TrafficAnalysisService.GetTrafficAnalysis:output_type -> ingate.admin.v1.GetTrafficAnalysisResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_admin_v1_traffic_analysis_proto_init() }
func file_admin_v1_traffic_analysis_proto_init() {
	if File_admin_v1_traffic_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_traffic_analysis_proto_rawDesc), len(file_admin_v1_traffic_analysis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_traffic_analysis_proto_goTypes,
		DependencyIndexes: file_admin_v1_traffic_analysis_proto_depIdxs,
		EnumInfos:         file_admin_v1_traffic_analysis_proto_enumTypes,
		MessageInfos:      file_admin_v1_traffic_analysis_proto_msgTypes,
	}.Build()
	File_admin_v1_traffic_analysis_proto = out.File
	file_admin_v1_traffic_analysis_proto_goTypes = nil
	file_admin_v1_traffic_analysis_proto_depIdxs = nil
}
