// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/lgc202/ingate/internal/apiserver/conf"
	"github.com/lgc202/ingate/internal/apiserver/server"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, server_HTTP *conf.Server_HTTP, server_Authentication *conf.Server_Authentication, data_Etcd *conf.Data_Etcd, logger *slog.Logger, apiserverServiceInstanceID serviceInstanceID) (*kratos.App, error) {
	serverServer, err := server.New(server_HTTP, server_Authentication, data_Etcd)
	if err != nil {
		return nil, err
	}
	app := newKratosApp(logger, confServer, serverServer, apiserverServiceInstanceID)
	return app, nil
}
