server:
  http:
    addr: "127.0.0.1:18443"
    cert_directory: "_output/certificates"
  shutdown_timeout: "30s"

data:
  etcd:
    endpoints:
      - "http://127.0.0.1:2379"
    prefix: "/registry/gateway.ingate.io"

logging:
  format: "json"
  level: "info"
  add_source: false
