server:
  grpc:
    addr: "127.0.0.1:18081"
  http:
    addr: "127.0.0.1:18082"
    timeout: "5s"
  shutdown_timeout: "30s"

data:
  apiserver:
    master: ""
    kubeconfig: "_output/kubeconfig"
  redis:
    address: "127.0.0.1:6379"
    password: ""
    database: 0
    dial_timeout: "2s"
    operation_timeout: "1s"

logging:
  format: "json"
  level: "info"
  add_source: false
