server:
  http:
    addr: ":8081"
    timeout: "30s"
  console_dir: "web/console/dist"
  shutdown_timeout: "30s"

data:
  admin_api:
    base_url: "http://127.0.0.1:8082"

logging:
  format: "json"
  level: "info"
  add_source: false
