server:
  listen_address: ":8082"

apiserver:
  master: ""
  kubeconfig: "_output/kubeconfig"

logging:
  format: "json"
  level: "info"
  add_source: false
  stdout: false
  file:
    path: "_output/logs/ingate-admin.log"
    max_size_mb: 100
    max_backups: 10
    max_age_days: 30
    compress: false
    local_time: false
