server:
  bind_address: "127.0.0.1"
  secure_port: 18443
  cert_directory: "_output/certificates"

storage:
  etcd_servers:
    - "http://127.0.0.1:2379"
  path_prefix: "/registry/gateway.ingate.io"

logging:
  format: "json"
  level: "info"
  add_source: false
  stdout: false
  file:
    path: "_output/logs/ingate-apiserver.log"
    max_size_mb: 100
    max_backups: 10
    max_age_days: 30
    compress: false
    local_time: false
