server:
  http:
    addr: "127.0.0.1:18082"
    timeout: "5s"
  grpc:
    addr: "127.0.0.1:18081"
  shutdown_timeout: "30s"

data:
  redis:
    address: "127.0.0.1:6379"
    password: ""
    database: 0

logging:
  format: "json"
  level: "info"
  add_source: false
