server:
  listen_address: ":8082"

apiserver:
  master: ""
  kubeconfig: "_output/kubeconfig"

mysql:
  dsn: "ingate:ingate@tcp(127.0.0.1:3306)/ingate?charset=utf8mb4&parseTime=true&loc=UTC&timeout=5s&readTimeout=5s&writeTimeout=5s"
  max_open_connections: 20
  max_idle_connections: 10
  connection_max_lifetime: "30m"

redis:
  address: "127.0.0.1:6379"
  password: ""
  database: 0

logging:
  format: "json"
  level: "info"
  add_source: false
  stdout: false
  file:
    path: "_output/logs/ingate-admin.log"
    max_size_mb: 100
    max_backups: 10
    max_age_days: 30
    compress: false
    local_time: false
