server:
  grpc:
    addr: "0.0.0.0:18081"
    tls:
      enabled: false
      cert_file: ""
      key_file: ""
      client_ca_file: ""
  http:
    addr: "0.0.0.0:18082"
    timeout: "5s"
  shutdown_timeout: "30s"

data:
  apiserver:
    master: ""
    kubeconfig: "/opt/ingate/ai-extproc/configs/kubeconfig.yaml"
    bearer_token: "${APISERVER_BEARER_TOKEN}"
  redis:
    address: "redis:6379"
    password: ""
    database: 0
    dial_timeout: "2s"
    operation_timeout: "1s"

logging:
  format: "json"
  level: "info"
  add_source: false
