// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package aiextproc

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/lgc202/ingate/internal/aiextproc/biz/tokenquota"
	"github.com/lgc202/ingate/internal/aiextproc/conf"
	"github.com/lgc202/ingate/internal/aiextproc/data"
	"github.com/lgc202/ingate/internal/aiextproc/data/apiserver"
	"github.com/lgc202/ingate/internal/aiextproc/data/redis"
	"github.com/lgc202/ingate/internal/aiextproc/server"
	"github.com/lgc202/ingate/internal/aiextproc/service"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, data_APIServer *conf.Data_APIServer, data_Redis *conf.Data_Redis, logger *slog.Logger, aiextprocServiceInstanceID serviceInstanceID) (*kratos.App, error) {
	configCache, err := apiserver.NewConfigCache(data_APIServer, logger)
	if err != nil {
		return nil, err
	}
	tokenCounter := redis.NewTokenCounter(data_Redis)
	readiness := data.NewReadiness(configCache, tokenCounter)
	limiter := tokenquota.NewLimiter(configCache, tokenCounter)
	externalProcessor := service.NewExternalProcessor(configCache, limiter, logger)
	httpServer := server.NewHTTPServer(confServer, readiness, externalProcessor)
	tokenQuotaUsageService := service.NewTokenQuotaUsageService(limiter, logger)
	grpcServer, err := server.NewGRPCServer(confServer, externalProcessor, tokenQuotaUsageService)
	if err != nil {
		return nil, err
	}
	app := newKratosApp(logger, confServer, httpServer, grpcServer, configCache, tokenCounter, aiextprocServiceInstanceID)
	return app, nil
}
