// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bootstrap 定义 ingate-admin-api 的完整进程配置
type Bootstrap struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Server         *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data           *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Logging        *Logging               `protobuf:"bytes,3,opt,name=logging,proto3" json:"logging,omitempty"`
	Authentication *Authentication        `protobuf:"bytes,4,opt,name=authentication,proto3" json:"authentication,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetLogging() *Logging {
	if x != nil {
		return x.Logging
	}
	return nil
}

func (x *Bootstrap) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apiserver     *Data_APIServer        `protobuf:"bytes,1,opt,name=apiserver,proto3" json:"apiserver,omitempty"`
	Mysql         *Data_MySQL            `protobuf:"bytes,2,opt,name=mysql,proto3" json:"mysql,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,3,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetApiserver() *Data_APIServer {
	if x != nil {
		return x.Apiserver
	}
	return nil
}

func (x *Data) GetMysql() *Data_MySQL {
	if x != nil {
		return x.Mysql
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

type Logging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	AddSource     bool                   `protobuf:"varint,3,opt,name=add_source,json=addSource,proto3" json:"add_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logging) Reset() {
	*x = Logging{}
	mi := &file_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logging) ProtoMessage() {}

func (x *Logging) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logging.ProtoReflect.Descriptor instead.
func (*Logging) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Logging) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Logging) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logging) GetAddSource() bool {
	if x != nil {
		return x.AddSource
	}
	return false
}

type Authentication struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Issuer           string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience         string                 `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	RolesClaim       string                 `protobuf:"bytes,4,opt,name=roles_claim,json=rolesClaim,proto3" json:"roles_claim,omitempty"`
	AdminRoles       []string               `protobuf:"bytes,5,rep,name=admin_roles,json=adminRoles,proto3" json:"admin_roles,omitempty"`
	OperatorRoles    []string               `protobuf:"bytes,6,rep,name=operator_roles,json=operatorRoles,proto3" json:"operator_roles,omitempty"`
	ViewerRoles      []string               `protobuf:"bytes,7,rep,name=viewer_roles,json=viewerRoles,proto3" json:"viewer_roles,omitempty"`
	DiscoveryTimeout *durationpb.Duration   `protobuf:"bytes,8,opt,name=discovery_timeout,json=discoveryTimeout,proto3" json:"discovery_timeout,omitempty"`
	ClientId         string                 `protobuf:"bytes,9,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scopes           []string               `protobuf:"bytes,10,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Authentication) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Authentication) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Authentication) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Authentication) GetRolesClaim() string {
	if x != nil {
		return x.RolesClaim
	}
	return ""
}

func (x *Authentication) GetAdminRoles() []string {
	if x != nil {
		return x.AdminRoles
	}
	return nil
}

func (x *Authentication) GetOperatorRoles() []string {
	if x != nil {
		return x.OperatorRoles
	}
	return nil
}

func (x *Authentication) GetViewerRoles() []string {
	if x != nil {
		return x.ViewerRoles
	}
	return nil
}

func (x *Authentication) GetDiscoveryTimeout() *durationpb.Duration {
	if x != nil {
		return x.DiscoveryTimeout
	}
	return nil
}

func (x *Authentication) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Authentication) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_APIServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Master        string                 `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,2,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_APIServer) Reset() {
	*x = Data_APIServer{}
	mi := &file_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_APIServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_APIServer) ProtoMessage() {}

func (x *Data_APIServer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_APIServer.ProtoReflect.Descriptor instead.
func (*Data_APIServer) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_APIServer) GetMaster() string {
	if x != nil {
		return x.Master
	}
	return ""
}

func (x *Data_APIServer) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

type Data_MySQL struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Dsn                   string                 `protobuf:"bytes,1,opt,name=dsn,proto3" json:"dsn,omitempty"`
	MaxOpenConnections    int32                  `protobuf:"varint,2,opt,name=max_open_connections,json=maxOpenConnections,proto3" json:"max_open_connections,omitempty"`
	MaxIdleConnections    int32                  `protobuf:"varint,3,opt,name=max_idle_connections,json=maxIdleConnections,proto3" json:"max_idle_connections,omitempty"`
	ConnectionMaxLifetime *durationpb.Duration   `protobuf:"bytes,4,opt,name=connection_max_lifetime,json=connectionMaxLifetime,proto3" json:"connection_max_lifetime,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Data_MySQL) Reset() {
	*x = Data_MySQL{}
	mi := &file_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MySQL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MySQL) ProtoMessage() {}

func (x *Data_MySQL) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MySQL.ProtoReflect.Descriptor instead.
func (*Data_MySQL) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_MySQL) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

func (x *Data_MySQL) GetMaxOpenConnections() int32 {
	if x != nil {
		return x.MaxOpenConnections
	}
	return 0
}

func (x *Data_MySQL) GetMaxIdleConnections() int32 {
	if x != nil {
		return x.MaxIdleConnections
	}
	return 0
}

func (x *Data_MySQL) GetConnectionMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnectionMaxLifetime
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Database      int32                  `protobuf:"varint,3,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_Redis) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Data_Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Data_Redis) GetDatabase() int32 {
	if x != nil {
		return x.Database
	}
	return 0
}

var File_conf_proto protoreflect.FileDescriptor

const file_conf_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"conf.proto\x12\x11ingate.admin.conf\x1a\x1egoogle/protobuf/duration.proto\"\xec\x01\n" +
	"\tBootstrap\x121\n" +
	"\x06server\x18\x01 \x01(\v2\x19.ingate.admin.conf.ServerR\x06server\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.ingate.admin.conf.DataR\x04data\x124\n" +
	"\alogging\x18\x03 \x01(\v2\x1a.ingate.admin.conf.LoggingR\alogging\x12I\n" +
	"\x0eauthentication\x18\x04 \x01(\v2!.ingate.admin.conf.AuthenticationR\x0eauthentication\"\xa7\x01\n" +
	"\x06Server\x122\n" +
	"\x04http\x18\x01 \x01(\v2\x1e.ingate.admin.conf.Server.HTTPR\x04http\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\xa4\x04\n" +
	"\x04Data\x12?\n" +
	"\tapiserver\x18\x01 \x01(\v2!.ingate.admin.conf.Data.APIServerR\tapiserver\x123\n" +
	"\x05mysql\x18\x02 \x01(\v2\x1d.ingate.admin.conf.Data.MySQLR\x05mysql\x123\n" +
	"\x05redis\x18\x03 \x01(\v2\x1d.ingate.admin.conf.Data.RedisR\x05redis\x1aC\n" +
	"\tAPIServer\x12\x16\n" +
	"\x06master\x18\x01 \x01(\tR\x06master\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x02 \x01(\tR\n" +
	"kubeconfig\x1a\xd0\x01\n" +
	"\x05MySQL\x12\x10\n" +
	"\x03dsn\x18\x01 \x01(\tR\x03dsn\x120\n" +
	"\x14max_open_connections\x18\x02 \x01(\x05R\x12maxOpenConnections\x120\n" +
	"\x14max_idle_connections\x18\x03 \x01(\x05R\x12maxIdleConnections\x12Q\n" +
	"\x17connection_max_lifetime\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x15connectionMaxLifetime\x1aY\n" +
	"\x05Redis\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\x05R\bdatabase\"V\n" +
	"\aLogging\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x1d\n" +
	"\n" +
	"add_source\x18\x03 \x01(\bR\taddSource\"\xe7\x02\n" +
	"\x0eAuthentication\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x03 \x01(\tR\baudience\x12\x1f\n" +
	"\vroles_claim\x18\x04 \x01(\tR\n" +
	"rolesClaim\x12\x1f\n" +
	"\vadmin_roles\x18\x05 \x03(\tR\n" +
	"adminRoles\x12%\n" +
	"\x0eoperator_roles\x18\x06 \x03(\tR\roperatorRoles\x12!\n" +
	"\fviewer_roles\x18\a \x03(\tR\vviewerRoles\x12F\n" +
	"\x11discovery_timeout\x18\b \x01(\v2\x19.google.protobuf.DurationR\x10discoveryTimeout\x12\x1b\n" +
	"\tclient_id\x18\t \x01(\tR\bclientId\x12\x16\n" +
	"\x06scopes\x18\n" +
	" \x03(\tR\x06scopesB6Z4github.com/lgc202/ingate/internal/adminapi/conf;confb\x06proto3"

var (
	file_conf_proto_rawDescOnce sync.Once
	file_conf_proto_rawDescData []byte
)

func file_conf_proto_rawDescGZIP() []byte {
	file_conf_proto_rawDescOnce.Do(func() {
		file_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)))
	})
	return file_conf_proto_rawDescData
}

var file_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: ingate.admin.conf.Bootstrap
	(*Server)(nil),              // 1: ingate.admin.conf.Server
	(*Data)(nil),                // 2: ingate.admin.conf.Data
	(*Logging)(nil),             // 3: ingate.admin.conf.Logging
	(*Authentication)(nil),      // 4: ingate.admin.conf.Authentication
	(*Server_HTTP)(nil),         // 5: ingate.admin.conf.Server.HTTP
	(*Data_APIServer)(nil),      // 6: ingate.admin.conf.Data.APIServer
	(*Data_MySQL)(nil),          // 7: ingate.admin.conf.Data.MySQL
	(*Data_Redis)(nil),          // 8: ingate.admin.conf.Data.Redis
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_conf_proto_depIdxs = []int32{
	1,  // 0: ingate.admin.conf.Bootstrap.server:type_name -> ingate.admin.conf.Server
	2,  // 1: ingate.admin.conf.Bootstrap.data:type_name -> ingate.admin.conf.Data
	3,  // 2: ingate.admin.conf.Bootstrap.logging:type_name -> ingate.admin.conf.Logging
	4,  // 3: ingate.admin.conf.Bootstrap.authentication:type_name -> ingate.admin.conf.Authentication
	5,  // 4: ingate.admin.conf.Server.http:type_name -> ingate.admin.conf.Server.HTTP
	6,  // 5: ingate.admin.conf.Data.apiserver:type_name -> ingate.admin.conf.Data.APIServer
	7,  // 6: ingate.admin.conf.Data.mysql:type_name -> ingate.admin.conf.Data.MySQL
	8,  // 7: ingate.admin.conf.Data.redis:type_name -> ingate.admin.conf.Data.Redis
	9,  // 8: ingate.admin.conf.Authentication.discovery_timeout:type_name -> google.protobuf.Duration
	9,  // 9: ingate.admin.conf.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	9,  // 10: ingate.admin.conf.Data.MySQL.connection_max_lifetime:type_name -> google.protobuf.Duration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_conf_proto_init() }
func file_conf_proto_init() {
	if File_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_proto_rawDesc), len(file_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_proto_goTypes,
		DependencyIndexes: file_conf_proto_depIdxs,
		MessageInfos:      file_conf_proto_msgTypes,
	}.Build()
	File_conf_proto = out.File
	file_conf_proto_goTypes = nil
	file_conf_proto_depIdxs = nil
}
